// Static seed data + shared types for the governance section.
// Votes are tracked separately in lib/governance/votes.ts (localStorage).
// Supabase persistence is a planned Part 2 addition.

export type ProposalCategory = "economic" | "political" | "social" | "information" | "democracy" | "technology" | "banking";

export interface Proposal {
  id: string;             // slug for seeded; uuid for user-submitted
  title: string;
  description: string;    // 2–3 sentence summary shown on card
  rationale: string;      // longer argument shown on detail page
  category: ProposalCategory;
  moduleSlug: string | null;
  moduleTitle: string | null;
  discussionThreadId?: string | null;
  discussionThreadTitle?: string | null;
  authorName: string;
  isSeeded: boolean;
  seedUpvotes: number;
  seedDownvotes: number;
  createdAt: string;      // ISO date string
}

export const CATEGORY_META: Record<ProposalCategory, { label: string; color: string; border: string; bg: string }> = {
  economic:    { label: "Economic",    color: "text-emerald-200", border: "border-emerald-400/30", bg: "bg-emerald-400/10" },
  political:   { label: "Political",   color: "text-amber-200",   border: "border-amber-400/30",   bg: "bg-amber-400/10"   },
  social:      { label: "Social",      color: "text-rose-200",    border: "border-rose-400/30",    bg: "bg-rose-400/10"    },
  information: { label: "Information", color: "text-cyan-200",    border: "border-cyan-400/30",    bg: "bg-cyan-400/10"    },
  democracy:   { label: "Democracy",    color: "text-violet-200", border: "border-violet-400/30", bg: "bg-violet-400/10"  },
  technology:  { label: "Technology",   color: "text-sky-200",    border: "border-sky-400/30",    bg: "bg-sky-400/10"     },
  banking:     { label: "Banking",      color: "text-teal-200",   border: "border-teal-400/30",   bg: "bg-teal-400/10"    },
};

export const SEEDED_PROPOSALS: Proposal[] = [
  // ── GDP & wellbeing ──────────────────────────────────────────────────────────
  {
    id: "genuine-progress-indicator",
    title: "Adopt a Genuine Progress Indicator as the official national accounting standard",
    description: "Replace GDP as the headline economic metric with the GPI, which accounts for inequality, environmental degradation, and unpaid care work. This would change what governments optimise for.",
    rationale: "GDP measures transaction volume, not human flourishing. Every traffic jam, divorce, and oil spill increases GDP. A GPI adds the value of volunteer work and subtracts the cost of pollution, crime, and inequality. Countries that have piloted GPI find it diverges sharply from GDP after the 1970s — giving policymakers an honest signal about whether growth is actually improving lives.",
    category: "economic",
    moduleSlug: "why-gdp-is-not-the-same-as-wellbeing",
    moduleTitle: "Why GDP is not the same as wellbeing",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 148,
    seedDownvotes: 12,
    createdAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "wellbeing-budget-mandate",
    title: "Mandate wellbeing metrics in all government budget decisions",
    description: "Require every ministry to assess and publish the wellbeing impact of proposed spending before approval. New Zealand's Wellbeing Budget is the model — make it legally binding, not optional.",
    rationale: "Most budget processes optimise for a narrow set of fiscal metrics and ignore distributional effects on health, time poverty, and community cohesion. Embedding wellbeing impact assessments into the budget cycle forces trade-offs to become visible. When mental health costs, care gaps, and loneliness are priced in, the calculus of 'efficiency' changes dramatically.",
    category: "political",
    moduleSlug: "why-gdp-is-not-the-same-as-wellbeing",
    moduleTitle: "Why GDP is not the same as wellbeing",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 112,
    seedDownvotes: 19,
    createdAt: "2024-11-02T00:00:00Z",
  },
  // ── Banks & money creation ────────────────────────────────────────────────────
  {
    id: "public-digital-currency",
    title: "Establish a central bank digital currency as a direct public money alternative",
    description: "Allow citizens and businesses to hold accounts directly at the central bank, bypassing commercial banks for basic transactions. This gives everyone access to sovereign money, not just bank-created credit.",
    rationale: "Over 97% of money in circulation is created by commercial banks as interest-bearing debt. A CBDC held at the central bank would give households a safe, interest-free settlement layer independent of private lending decisions. It would reduce systemic risk, enable targeted fiscal transfers, and break the feedback loop where banks expand credit for profit rather than social need.",
    category: "economic",
    moduleSlug: "how-banks-create-money",
    moduleTitle: "How banks create money",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 201,
    seedDownvotes: 47,
    createdAt: "2024-11-03T00:00:00Z",
  },
  {
    id: "full-reserve-banking-pilot",
    title: "Pilot full-reserve banking in one national institution to test the alternative",
    description: "Create a state-backed bank that cannot lend out more than it holds in deposits. Use it to benchmark stability, credit availability, and inflation impact against the fractional-reserve system.",
    rationale: "The debate between fractional and full-reserve banking is largely theoretical because no major economy has run the experiment. A state-backed pilot would produce empirical data on how lending, money supply, and investment behave under different reserve rules — ending the speculation with evidence.",
    category: "economic",
    moduleSlug: "how-banks-create-money",
    moduleTitle: "How banks create money",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 87,
    seedDownvotes: 34,
    createdAt: "2024-11-04T00:00:00Z",
  },
  // ── Wealth compounding ────────────────────────────────────────────────────────
  {
    id: "progressive-wealth-tax",
    title: "Introduce a progressive annual wealth tax above €10M",
    description: "Tax net wealth above €10M at 1–2% per year, with higher rates above €100M and €1B. Revenue to fund public investment, not income tax cuts.",
    rationale: "Capital returns compound at 4–8% per year while wages grow at 1–2%. Without redistribution, wealth concentrates toward a shrinking class regardless of individual effort. An annual wealth tax disrupts the compounding loop at the top without affecting the vast majority of households. France, Norway, and Switzerland run versions of it. The main challenge is capital flight — solvable with global minimum standards.",
    category: "economic",
    moduleSlug: "how-wealth-compounds-faster-than-wages",
    moduleTitle: "How wealth compounds faster than wages",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 263,
    seedDownvotes: 91,
    createdAt: "2024-11-05T00:00:00Z",
  },
  {
    id: "pay-ratio-cap",
    title: "Cap the CEO-to-median-worker pay ratio at 20:1 for publicly listed companies",
    description: "Require that the highest paid executive at any listed company earns no more than 20 times the median employee salary. Excess must be distributed as profit-sharing or invested in wages.",
    rationale: "In 1965, the average US CEO-to-worker pay ratio was 20:1. By 2022 it was over 350:1. This is not driven by productivity but by board dynamics, stock options, and winner-takes-most market structures. A statutory ratio creates a direct link between executive reward and workforce pay — making wage growth the precondition for personal wealth at the top.",
    category: "economic",
    moduleSlug: "how-wealth-compounds-faster-than-wages",
    moduleTitle: "How wealth compounds faster than wages",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 198,
    seedDownvotes: 73,
    createdAt: "2024-11-06T00:00:00Z",
  },
  // ── Tax havens ────────────────────────────────────────────────────────────────
  {
    id: "global-minimum-corporate-tax",
    title: "Enforce the OECD 15% global minimum corporate tax and push for 25%",
    description: "The OECD's 15% global minimum is a floor — advocate for 25% and close the loopholes that let multinationals still shift profits through substance requirements. Revenue stays in the country where economic activity happens.",
    rationale: "Tax havens cost governments an estimated $500–800B per year. The OECD deal at 15% is a start but still well below the rates that existed before the 1980s race-to-the-bottom. Raising the floor to 25% and closing carve-outs (particularly for IP income) would materially restore public capacity to fund health, education, and infrastructure.",
    category: "economic",
    moduleSlug: "how-tax-havens-drain-public-revenue",
    moduleTitle: "How tax havens drain public revenue",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 174,
    seedDownvotes: 28,
    createdAt: "2024-11-07T00:00:00Z",
  },
  {
    id: "beneficial-ownership-registry",
    title: "Mandate public beneficial ownership registries in all G20 jurisdictions",
    description: "Every company, trust, and foundation must publicly disclose its ultimate human owner. No more anonymous shell companies. Registries must be public, machine-readable, and cross-referenced internationally.",
    rationale: "Tax evasion, corruption, and money laundering all rely on beneficial ownership opacity. The UK's Companies House reform and the EU's AML directives show it's technically and legally feasible. Making registries public (not just available to regulators) creates a layer of civil society oversight that regulators alone cannot provide.",
    category: "political",
    moduleSlug: "how-tax-havens-drain-public-revenue",
    moduleTitle: "How tax havens drain public revenue",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 155,
    seedDownvotes: 21,
    createdAt: "2024-11-08T00:00:00Z",
  },
  // ── Lobbying ──────────────────────────────────────────────────────────────────
  {
    id: "revolving-door-ban",
    title: "Impose a 5-year cooling-off period between regulatory roles and the industries they oversaw",
    description: "No regulator, minister, or senior civil servant should be able to take a job in the sector they regulated within 5 years of leaving office. Violations attract criminal penalties, not just fines.",
    rationale: "The revolving door creates a structural incentive for regulators to go easy on future employers. Weak cooling-off periods (the current standard is 1–2 years) are insufficient — a 5-year bar changes career incentives. Criminal penalties matter because monetary fines are often priced-in as a cost of doing business.",
    category: "political",
    moduleSlug: "how-lobbying-shapes-policy",
    moduleTitle: "How lobbying shapes policy",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 231,
    seedDownvotes: 18,
    createdAt: "2024-11-09T00:00:00Z",
  },
  {
    id: "lobbying-spending-caps",
    title: "Introduce mandatory real-time lobbying registries with binding annual spending caps",
    description: "All lobbying activity must be registered within 48 hours and published in a public database. Annual caps on total lobbying spend per organisation prevent arms-race escalation.",
    rationale: "Unregistered lobbying — through industry associations, think tanks, and advisory panels — dwarfs formal lobbying disclosures. Real-time registration closes the gap. Spending caps prevent any single industry from dominating policy attention through sheer financial weight, restoring some parity between well-resourced and poorly-resourced interests.",
    category: "political",
    moduleSlug: "how-lobbying-shapes-policy",
    moduleTitle: "How lobbying shapes policy",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 189,
    seedDownvotes: 35,
    createdAt: "2024-11-10T00:00:00Z",
  },
  // ── Electoral rules ───────────────────────────────────────────────────────────
  {
    id: "ranked-choice-voting",
    title: "Adopt ranked-choice voting for all national elections",
    description: "Replace first-past-the-post with ranked-choice voting so that the winner has genuine majority support. Eliminates strategic voting and reduces the two-party duopoly.",
    rationale: "First-past-the-post allows candidates to win with 35% of the vote while 65% preferred someone else. RCV requires winners to build broad coalitions. Countries using preferential voting systems (Australia, Ireland) consistently produce more representative parliaments and higher voter engagement. The 'spoiler effect' that punishes third-party voting disappears.",
    category: "political",
    moduleSlug: "how-electoral-rules-shape-political-power",
    moduleTitle: "How electoral rules shape political power",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 302,
    seedDownvotes: 64,
    createdAt: "2024-11-11T00:00:00Z",
  },
  {
    id: "proportional-representation",
    title: "Move to proportional representation for all legislative bodies",
    description: "Ensure that a party winning 30% of votes gets approximately 30% of seats. Mixed-member proportional systems (Germany, New Zealand) combine local representation with proportional outcomes.",
    rationale: "Winner-takes-all districts systematically waste votes and entrench geographical sorting. Proportional systems produce parliaments that more accurately reflect the electorate, increase the representation of women and minorities, and reduce polarisation because parties must negotiate rather than rule by bare majority. The evidence from 36 democracies is that PR produces better policy outcomes on equality and environmental protection.",
    category: "political",
    moduleSlug: "how-electoral-rules-shape-political-power",
    moduleTitle: "How electoral rules shape political power",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 278,
    seedDownvotes: 82,
    createdAt: "2024-11-12T00:00:00Z",
  },
  // ── Corruption ────────────────────────────────────────────────────────────────
  {
    id: "public-asset-declarations",
    title: "Require annual public asset and income declarations from all elected and senior appointed officials",
    description: "Every elected politician and senior civil servant must publish a complete declaration of assets, income sources, and liabilities each year. Failure to declare or false declarations attract mandatory criminal prosecution.",
    rationale: "Corruption thrives on opacity. Public declarations change the cost-benefit calculation for officials considering extraction or conflicts of interest — the public becomes the auditor. Ukraine's e-declaration system, despite its flaws, produced useful accountability data. Making declarations machine-readable allows civil society organisations to cross-reference them against procurement records automatically.",
    category: "political",
    moduleSlug: "how-corruption-behaves-like-a-hidden-tax",
    moduleTitle: "How corruption behaves like a hidden tax",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 241,
    seedDownvotes: 14,
    createdAt: "2024-11-13T00:00:00Z",
  },
  {
    id: "independent-anti-corruption-courts",
    title: "Establish independent anti-corruption courts insulated from political interference",
    description: "Create dedicated court chambers for corruption cases staffed by internationally vetted judges on fixed-term contracts. Remove the cases from the general judiciary where political pressure is easier to apply.",
    rationale: "In high-corruption environments, the judiciary is often compromised. Ukraine's High Anti-Corruption Court — created under international pressure in 2019 — demonstrates that a structurally separate court with transparent selection can operate more independently than the general system. The key design elements are public selection processes, international observer panels, and judges who cannot be transferred or dismissed by the executive.",
    category: "political",
    moduleSlug: "how-corruption-behaves-like-a-hidden-tax",
    moduleTitle: "How corruption behaves like a hidden tax",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 196,
    seedDownvotes: 22,
    createdAt: "2024-11-14T00:00:00Z",
  },
  // ── Media incentives ──────────────────────────────────────────────────────────
  {
    id: "public-media-endowment",
    title: "Replace advertising-funded news with a permanent public media endowment",
    description: "Create an independently governed endowment fund — seeded by a levy on digital advertising platforms — that distributes grants to qualifying news organisations based on reach and editorial independence, not government approval.",
    rationale: "Advertising-funded news creates a structural incentive to maximise engagement, which algorithms have proven means outrage. A levy on platforms that aggregated and monetised journalism's audience without funding its production is both fair and technically feasible. The BBC, NPR, and RNZ models show that public funding can coexist with editorial independence when governance structures are designed correctly.",
    category: "information",
    moduleSlug: "how-media-incentives-produce-outrage",
    moduleTitle: "How media incentives produce outrage",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 167,
    seedDownvotes: 53,
    createdAt: "2024-11-15T00:00:00Z",
  },
  {
    id: "platform-algorithmic-audits",
    title: "Mandate annual third-party algorithmic audits of all news-amplifying platforms",
    description: "Require platforms with over 10M monthly users to submit their content recommendation algorithms to independent auditors, with findings published publicly. Auditors assess for outrage amplification, misinformation promotion, and demographic targeting.",
    rationale: "Platform algorithms are among the most consequential editorial decisions in modern media — but they operate with zero transparency. Algorithmic audits (as proposed by the EU's Digital Services Act) create accountability without requiring governments to control content. The audit results allow regulators, researchers, and the public to assess whether recommendations are causing measurable harms.",
    category: "information",
    moduleSlug: "how-media-incentives-produce-outrage",
    moduleTitle: "How media incentives produce outrage",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 210,
    seedDownvotes: 41,
    createdAt: "2024-11-16T00:00:00Z",
  },
  // ── Surveillance capitalism ───────────────────────────────────────────────────
  {
    id: "ban-behavioural-advertising",
    title: "Classify personal behavioural data as a commons and ban its use for targeted advertising",
    description: "Prohibit the collection, sale, and use of individual behavioural profiles for commercial advertising. Contextual advertising (based on what you're reading, not who you are) remains permitted.",
    rationale: "Behavioural advertising is the business model that incentivises mass surveillance. Banning it does not ban advertising — it bans the surveillance layer underneath it. Norway's Consumer Council has demonstrated that contextual advertising is commercially viable and preferred by publishers for brand safety. Removing the surveillance incentive restructures the entire attention economy.",
    category: "information",
    moduleSlug: "how-surveillance-capitalism-shapes-attention",
    moduleTitle: "How surveillance capitalism shapes attention",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 289,
    seedDownvotes: 67,
    createdAt: "2024-11-17T00:00:00Z",
  },
  {
    id: "algorithmic-explanation-right",
    title: "Legislate a right to a meaningful explanation for all consequential algorithmic decisions",
    description: "Any automated decision affecting employment, credit, housing, healthcare, or legal status must be explainable to the affected individual in plain language, with a right to human review.",
    rationale: "GDPR Article 22 already provides a partial right not to be subject to automated decisions — but 'meaningful explanation' has been weakly enforced. Strengthening this right and extending it to consequential (not just fully automated) decisions would require systems to be designed for explainability from the start, rather than as an afterthought. It also gives individuals a practical route to challenge discriminatory algorithmic outcomes.",
    category: "information",
    moduleSlug: "how-surveillance-capitalism-shapes-attention",
    moduleTitle: "How surveillance capitalism shapes attention",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 198,
    seedDownvotes: 29,
    createdAt: "2024-11-18T00:00:00Z",
  },
  // ── Cities ────────────────────────────────────────────────────────────────────
  {
    id: "fifteen-minute-city-mandate",
    title: "Require 15-minute city planning standards for all new urban developments",
    description: "Planning law should require that any new residential development places residents within 15 minutes' walk or cycle of essential services: schools, healthcare, groceries, green space, and public transit.",
    rationale: "Car-dependent urban sprawl is not a natural outcome — it's a regulatory choice made in the mid-20th century. The 15-minute city model, piloted in Paris and Melbourne, shows that mixed-use zoning and street design can dramatically reduce car dependency, improve health outcomes, and cut emissions. Mandating it for new development is less disruptive than retrofitting existing cities and locks in the principle for future growth.",
    category: "social",
    moduleSlug: "why-cities-create-stress-or-freedom",
    moduleTitle: "Why cities create stress or freedom",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 156,
    seedDownvotes: 38,
    createdAt: "2024-11-19T00:00:00Z",
  },
  {
    id: "car-free-city-centers",
    title: "Mandate car-free city centers in all cities over 300,000 people by 2035",
    description: "Restrict private car access to city centers in major urban areas, replacing road space with public transit, cycling infrastructure, and pedestrian zones. Exemptions for emergency, delivery, and disability access.",
    rationale: "Oslo, Amsterdam, and Ghent have demonstrated that car-free or car-limited centers increase retail footfall, reduce pollution, and improve mental health for residents. The political resistance is largely from incumbent businesses who overestimate car-borne customers — post-implementation data consistently shows higher foot traffic. A national mandate removes the political risk from individual city governments.",
    category: "social",
    moduleSlug: "why-cities-create-stress-or-freedom",
    moduleTitle: "Why cities create stress or freedom",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 143,
    seedDownvotes: 61,
    createdAt: "2024-11-20T00:00:00Z",
  },
  // ── Housing ───────────────────────────────────────────────────────────────────
  {
    id: "vacancy-tax",
    title: "Introduce a progressive vacancy tax on investment properties held empty",
    description: "Tax residential properties left empty for more than 6 months per year at an escalating annual rate: 1% of assessed value in year one, rising to 5% by year three. Revenue funds social housing construction.",
    rationale: "In most major cities, tens of thousands of properties sit empty as financial assets while households are priced out or homeless. A vacancy tax changes the cost calculus for holding empty property. Vancouver's Empty Homes Tax (introduced 2017) raised occupancy rates and funded affordable housing simultaneously. The key implementation challenge is defining 'empty' — solved by utility usage data cross-referenced with tenancy registrations.",
    category: "economic",
    moduleSlug: "why-housing-becomes-financialized",
    moduleTitle: "Why housing becomes financialized",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 317,
    seedDownvotes: 43,
    createdAt: "2024-11-21T00:00:00Z",
  },
  {
    id: "community-land-trusts",
    title: "Scale community land trusts as the primary vehicle for new affordable housing",
    description: "Publicly fund the land acquisition for community land trusts in high-cost cities. CLTs own the land in perpetuity, leasing it to residents who own the buildings — permanently decoupling housing from speculative markets.",
    rationale: "Every generation of affordable housing built on market land eventually becomes unaffordable when subsidies expire or properties are sold. Community land trusts break this cycle by removing land from the market permanently. Burlington, Vermont's CLT (founded 1984) has maintained affordability through multiple real estate cycles. Scaling the model requires public land transfer — a policy choice, not a technical barrier.",
    category: "social",
    moduleSlug: "why-housing-becomes-financialized",
    moduleTitle: "Why housing becomes financialized",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 224,
    seedDownvotes: 31,
    createdAt: "2024-11-22T00:00:00Z",
  },

  // ── Direct democracy ────────────────────────────────────────────────────────
  {
    id: "liquid-democracy-platform",
    title: "Build a national liquid democracy platform for direct citizen participation in legislation",
    description: "Citizens can vote directly on any piece of legislation or delegate their vote to a trusted expert or representative on specific topics. Delegation is revocable at any time. Votes are public and cryptographically verifiable.",
    rationale: "Liquid democracy combines the scale of representative democracy with the directness of direct democracy. Instead of a fixed delegation every 4 years, citizens can delegate their vote on climate policy to a climate scientist, on tax law to an economist, and vote directly on issues they care about personally. Taiwan's vTaiwan platform has successfully used digital deliberation to produce consensus on contentious tech regulation. Scaling this to full legislative participation is now technically feasible.",
    category: "democracy",
    moduleSlug: "how-electoral-rules-shape-political-power",
    moduleTitle: "How electoral rules shape political power",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 342,
    seedDownvotes: 87,
    createdAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "citizens-assemblies-mandate",
    title: "Mandate citizens' assemblies for all major constitutional and structural policy decisions",
    description: "Before any structural reform — constitutional change, electoral reform, climate policy, healthcare restructuring — convene a randomly selected, demographically representative citizens' assembly to deliberate and produce recommendations. Parliament must respond formally.",
    rationale: "Citizens' assemblies have produced better outcomes than parliamentary processes on the most politically toxic issues: Ireland's abortion referendum, the UK Climate Assembly, French Citizens' Convention for Climate. Random selection (sortition) removes electoral incentives that distort representative democracy. Participants, given time and expert briefings, consistently reach more nuanced and sustainable conclusions than party politicians. The model scales — Denmark, Belgium, and France have run them nationally.",
    category: "democracy",
    moduleSlug: "how-electoral-rules-shape-political-power",
    moduleTitle: "How electoral rules shape political power",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 278,
    seedDownvotes: 54,
    createdAt: "2024-12-02T00:00:00Z",
  },
  {
    id: "sortition-upper-chamber",
    title: "Replace appointed upper chambers with randomly selected citizen chambers (sortition)",
    description: "Abolish appointed senates and Lords. Replace with a chamber of randomly selected citizens serving fixed 2-year terms with full legislative powers. Demographically stratified selection ensures representation by age, region, income, and education.",
    rationale: "Most upper chambers are either party-dominated extensions of lower chambers or undemocratic appointments by executives. Neither produces genuine revision or accountability. A sortition chamber introduces citizens with no electoral incentive — they cannot be re-selected — whose sole job is to scrutinise legislation on its merits. Ancient Athens used sortition for its governing councils; modern political theory has developed robust frameworks for scaling it. The Belgian G1000 experiment and French Convention demonstrated that ordinary citizens can handle complex policy.",
    category: "democracy",
    moduleSlug: "how-electoral-rules-shape-political-power",
    moduleTitle: "How electoral rules shape political power",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 213,
    seedDownvotes: 98,
    createdAt: "2024-12-03T00:00:00Z",
  },
  {
    id: "participatory-budgeting-national",
    title: "Allocate 10% of public budgets to participatory budgeting decided by direct citizen vote",
    description: "Ring-fence 10% of national and municipal budgets for direct citizen allocation. Proposals submitted by any resident, deliberated in public forums, and voted on by all eligible citizens. Results are binding.",
    rationale: "Porto Alegre invented participatory budgeting in 1989 and produced measurable improvements in public investment quality and trust in government. New York City, Paris, and Lisbon have run it at scale. When citizens decide directly where money goes, they make different choices than politicians — typically prioritising basic infrastructure, health, and education over prestige projects. The 10% threshold is large enough to matter but small enough to be politically feasible.",
    category: "democracy",
    moduleSlug: "how-corruption-behaves-like-a-hidden-tax",
    moduleTitle: "How corruption behaves like a hidden tax",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 298,
    seedDownvotes: 45,
    createdAt: "2024-12-04T00:00:00Z",
  },
  {
    id: "mandatory-term-limits",
    title: "Impose mandatory term limits and a maximum age cap of 75 for all elected officials",
    description: "No elected official may serve more than 12 cumulative years in any single office. No person above the age of 75 may stand for or continue in elected national office. Both rules apply to executive and legislative positions.",
    rationale: "Long incumbency produces entrenchment, ossified networks, and cognitive capture. The US Senate's average age is now 65; the EU Commission has routinely been led by officials in their 70s. Term limits force renewal and reduce the career-incentive distortions that make politicians prioritise re-election over good policy. An age cap is not discriminatory — it is a recognition that executive cognitive function, accountability cycles, and generational representation all matter.",
    category: "democracy",
    moduleSlug: "how-lobbying-shapes-policy",
    moduleTitle: "How lobbying shapes policy",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 387,
    seedDownvotes: 112,
    createdAt: "2024-12-05T00:00:00Z",
  },
  {
    id: "public-campaign-finance",
    title: "Replace all private political donations with a universal public campaign finance system",
    description: "Abolish private and corporate political donations above €100. Replace with equal public grants to qualifying parties, plus a voucher system giving every citizen €50 per election cycle to allocate to any registered party or candidate.",
    rationale: "Private campaign finance is institutionalised corruption. The citizen voucher system (proposed by Weyl and Posner) is particularly powerful: it gives every citizen the same political spending power, not just the wealthy. France and Germany already have strong public finance regimes — the evidence shows it reduces capture without harming political competition. The voucher component creates an active connection between citizens and political parties without mandating participation.",
    category: "democracy",
    moduleSlug: "how-lobbying-shapes-policy",
    moduleTitle: "How lobbying shapes policy",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 334,
    seedDownvotes: 78,
    createdAt: "2024-12-06T00:00:00Z",
  },
  // ── Technology & governance ──────────────────────────────────────────────────
  {
    id: "open-government-data-mandate",
    title: "Mandate real-time publication of all public spending, contracts, and decisions in machine-readable format",
    description: "Every public expenditure above €1,000, every contract awarded, every regulatory decision, and every parliamentary vote must be published in a structured, machine-readable format within 72 hours. No exemptions for 'commercial sensitivity' in public contracts.",
    rationale: "Opacity is the primary precondition for corruption. When spending data is machine-readable, journalists, academics, and automated systems can monitor procurement in real time. Ukraine's ProZorro system — open-source procurement transparency — saved an estimated $1B in its first year by making contract awards immediately visible. The UK's Contracts Finder and EU's TED database are partial implementations — mandating completeness and machine-readability closes the gap.",
    category: "technology",
    moduleSlug: "how-corruption-behaves-like-a-hidden-tax",
    moduleTitle: "How corruption behaves like a hidden tax",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 256,
    seedDownvotes: 31,
    createdAt: "2024-12-07T00:00:00Z",
  },
  {
    id: "ai-conflict-of-interest-detection",
    title: "Deploy AI systems to automatically detect and publish conflicts of interest in all parliamentary votes",
    description: "Mandate real-time cross-referencing of every parliamentary vote with the voting member's disclosed assets, donations received, and lobbying contacts. Automatic flagging of potential conflicts published publicly before the vote is finalised.",
    rationale: "Conflict of interest monitoring currently relies on self-declaration and reactive journalism. An automated system that cross-references voting records against financial interests, lobbying meetings, and campaign donors would flag patterns that no individual journalist can track across hundreds of legislators simultaneously. The data already exists — asset declarations, lobbying registers, donation records — it just isn't systematically cross-referenced. This is an AI application with unambiguous public benefit.",
    category: "technology",
    moduleSlug: "how-lobbying-shapes-policy",
    moduleTitle: "How lobbying shapes policy",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 312,
    seedDownvotes: 43,
    createdAt: "2024-12-08T00:00:00Z",
  },
  {
    id: "digital-identity-egovernance",
    title: "Build a universal digital identity and e-governance platform (Estonia model) in every democracy",
    description: "Provide every citizen with a secure digital identity usable for voting, tax filing, healthcare access, and government service interactions. All services accessible online with legal equivalence to in-person interactions. Open-source, interoperable infrastructure.",
    rationale: "Estonia has run 99% of government services digitally since 2000, saving an estimated 2% of GDP per year in administrative friction. The technical architecture — X-Road data exchange, digital signatures, and e-Residency — is open source and exportable. Digital identity infrastructure is the prerequisite for everything else: direct democracy, transparent spending, automated conflict detection. The barrier is political will, not technical capability.",
    category: "technology",
    moduleSlug: null,
    moduleTitle: null,
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 289,
    seedDownvotes: 67,
    createdAt: "2024-12-09T00:00:00Z",
  },
  {
    id: "open-source-government-software",
    title: "Mandate that all government software be open source and publicly auditable",
    description: "Any software built for or by government using public funds must be published as open source within 90 days of deployment. Voting systems, benefit calculation algorithms, tax systems, and judicial scoring tools must be independently auditable by any citizen.",
    rationale: "Proprietary government software creates vendor lock-in, prevents public scrutiny of consequential algorithms, and concentrates technical power. The EU's Public Money Public Code initiative has demonstrated the policy framework. Open-source government software can be audited for bias, security vulnerabilities, and errors that no internal team would catch — the same model that makes Linux more secure than proprietary operating systems. Voting systems in particular must never be a black box.",
    category: "technology",
    moduleSlug: "how-surveillance-capitalism-shapes-attention",
    moduleTitle: "How surveillance capitalism shapes attention",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 234,
    seedDownvotes: 52,
    createdAt: "2024-12-10T00:00:00Z",
  },
  {
    id: "blockchain-procurement-audit",
    title: "Record all public procurement on a public permissioned blockchain for immutable audit trails",
    description: "Every public contract — award, amendments, payments, and performance evaluations — recorded on a public blockchain. Records are immutable, timestamped, and publicly accessible. Enables automated detection of bid rigging, artificial splitting, and sole-source abuse.",
    rationale: "Contract manipulation is the most common form of public corruption worldwide. The immutability of blockchain records means that no official can retroactively alter procurement records after an investigation begins. Georgia's land registry blockchain eliminated property fraud; Ukraine's ProZorro blockchain procurement system won the Open Government Partnership Award. The technology is mature — the barrier is political resistance from those who benefit from opacity.",
    category: "technology",
    moduleSlug: "how-corruption-behaves-like-a-hidden-tax",
    moduleTitle: "How corruption behaves like a hidden tax",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 198,
    seedDownvotes: 44,
    createdAt: "2024-12-11T00:00:00Z",
  },
  {
    id: "digital-rights-constitution",
    title: "Enshrine digital rights — privacy, algorithmic transparency, and internet access — in national constitutions",
    description: "Constitutionally guarantee: the right to privacy from both state and corporate surveillance; the right to meaningful explanation of algorithmic decisions affecting you; the right to affordable internet access as a public utility; and the right to vote using secure digital infrastructure.",
    rationale: "Fundamental rights that exist only in legislation can be reversed by future parliaments. Constitutional protection makes them durable. Ecuador and Turkey have already constitutionalised internet access. The EU's Charter of Fundamental Rights includes data protection — but falls short on algorithmic transparency. Constitutionalising these rights forces them into judicial review and signals their priority against commercial and state interests.",
    category: "technology",
    moduleSlug: "how-surveillance-capitalism-shapes-attention",
    moduleTitle: "How surveillance capitalism shapes attention",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 267,
    seedDownvotes: 38,
    createdAt: "2024-12-12T00:00:00Z",
  },

  // ── Banking system reform ────────────────────────────────────────────────────
  {
    id: "sovereign-money-creation",
    title: "Transfer money creation from commercial banks to a democratically accountable public authority",
    description: "End the private bank monopoly on money creation. New money should be created by a public monetary authority, debt-free, and allocated through democratic processes — not as interest-bearing loans for profit.",
    rationale: "Over 97% of money in circulation is created by commercial banks as interest-bearing debt. This means the money supply itself grows only through the accumulation of debt — a structural driver of boom-bust cycles, inequality, and environmental overshoot. The Positive Money / Sovereign Money framework proposes that a public monetary authority creates money debt-free and allocates it via elected government for public purposes. Switzerland's 2018 Vollgeld Initiative demonstrated serious public appetite for this reform. Iceland's 2015 parliamentary report formally endorsed the proposal.",
    category: "banking",
    moduleSlug: "how-banks-create-money",
    moduleTitle: "How banks create money",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 312,
    seedDownvotes: 89,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "full-separation-retail-investment",
    title: "Reinstate strict separation between retail/deposit banking and investment banking (Glass-Steagall 2.0)",
    description: "No institution may simultaneously hold retail deposits and engage in securities trading, derivatives, or proprietary investment. A bank that takes deposits from households cannot use those deposits to speculate.",
    rationale: "The US Glass-Steagall Act (1933) enforced this separation after the Great Depression. Its repeal by Gramm-Leach-Bliley in 1999 directly enabled the risk structures that caused the 2008 crisis. When investment losses can cascade into retail deposit books, taxpayers become implicit insurers of speculative trading. Strict separation means investment banks fail without threatening the payments system. The EU's Liikanen Report (2012) and Vickers Report (UK, 2011) both recommended versions of this — implementation was watered down under industry pressure.",
    category: "banking",
    moduleSlug: "how-the-2008-financial-crisis-happened",
    moduleTitle: "How the 2008 Financial Crisis Happened",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 278,
    seedDownvotes: 54,
    createdAt: "2025-01-02T00:00:00Z",
  },
  {
    id: "public-banking-network",
    title: "Build a national network of public banks with a social mandate — not a profit mandate",
    description: "Establish publicly owned banks in every region with a statutory mandate to provide affordable credit for housing, small business, education, and green investment. Profits return to the public. No shareholder extraction.",
    rationale: "Germany's Sparkassen (savings banks) and KfW (development bank) networks demonstrate that public banking with a social mandate outperforms private banks on financial inclusion, SME lending, and regional economic development — while remaining financially stable across multiple crises. North Dakota's state bank has operated profitably since 1919. Public banks can offer mortgages and business loans at near-cost because they do not need to generate returns for shareholders — making homeownership and investment accessible without the debt trap.",
    category: "banking",
    moduleSlug: "how-banks-create-money",
    moduleTitle: "How banks create money",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 341,
    seedDownvotes: 67,
    createdAt: "2025-01-03T00:00:00Z",
  },
  {
    id: "interest-free-public-credit",
    title: "Offer interest-free public credit for housing, education, healthcare, and green transition",
    description: "Public banks and the central bank should offer zero-interest loans for socially essential purposes: first-home purchase, tertiary education, healthcare costs, and approved green infrastructure. Administrative fees only — no compounding interest.",
    rationale: "Interest on debt is not a natural law — it is a policy choice. Islamic banking prohibits riba (interest) on moral grounds and has developed viable profit-sharing alternatives for 40+ years across $3tn in assets. The argument for interest-free public credit in social categories is straightforward: when housing, education, or healthcare is funded by compound-interest debt, debt service consumes an increasing share of income for essential goods that should be universal rights. Interest-free public credit is not utopian — it is already how many central banks fund government deficits in practice.",
    category: "banking",
    moduleSlug: "how-banking-crises-repeat",
    moduleTitle: "Why Banking Crises Keep Happening",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 298,
    seedDownvotes: 102,
    createdAt: "2025-01-04T00:00:00Z",
  },
  {
    id: "cooperative-banking-mandate",
    title: "Require that at least 30% of the banking sector by assets be held in cooperative or mutual structures",
    description: "Mandate a minimum market share for cooperative banks, credit unions, and mutual building societies. Provide regulatory advantages (lower capital surcharges, access to central bank facilities) to cooperative structures to level the playing field against shareholder banks.",
    rationale: "Cooperative and mutual banks are owned by their members, not external shareholders. This changes the fundamental incentive: profit extraction is replaced by member benefit. European cooperative banks (Rabobank, Crédit Agricole, DZ Bank) consistently outperformed shareholder banks in 2008 on stability and continued lending. Credit unions serve lower-income communities that shareholder banks systematically underserve. A 30% floor prevents the cooperative sector from being slowly displaced through regulatory disadvantage.",
    category: "banking",
    moduleSlug: null,
    moduleTitle: null,
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 213,
    seedDownvotes: 45,
    createdAt: "2025-01-05T00:00:00Z",
  },
  {
    id: "green-lending-mandates",
    title: "Require all banks to align lending portfolios with Paris Agreement targets by 2030",
    description: "Banks must phase out financing for new fossil fuel projects and demonstrate by 2030 that their full lending portfolio is Paris-aligned. Non-compliant banks face escalating capital surcharges. Transition plans must be published annually and independently audited.",
    rationale: "Banks are the primary financiers of the fossil fuel economy. Since the Paris Agreement in 2015, the 60 largest banks have provided $6.9tn in financing to fossil fuel companies. Without mandatory portfolio alignment, voluntary ESG commitments remain greenwashing. The ECB and Bank of England have both confirmed that unmanaged climate risk is a systemic financial risk — mandatory alignment is therefore both climate policy and financial stability policy. The Net-Zero Banking Alliance commitments cover the framework; what is missing is legal enforceability.",
    category: "banking",
    moduleSlug: null,
    moduleTitle: null,
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 267,
    seedDownvotes: 78,
    createdAt: "2025-01-06T00:00:00Z",
  },
  {
    id: "universal-basic-banking",
    title: "Guarantee every resident a free basic bank account and digital payment access as a public utility",
    description: "No resident should be excluded from the financial system. Mandate a universal basic account — free transactions, savings, and digital payments — provided through the central bank, postal network, or licensed public institution. No fees, no credit checks, no minimum balance.",
    rationale: "1.4 billion adults globally remain unbanked, and financial exclusion directly reinforces poverty traps. In wealthy countries, predatory check-cashing services and payday lenders fill the gap left by commercial banks who find low-income customers unprofitable. A universal basic account decouples financial access from commercial viability. India's Jan Dhan Yojana opened 500M accounts in 4 years using the postal network. The UK Post Office already provides basic accounts — making it universal and fee-free is a policy decision.",
    category: "banking",
    moduleSlug: null,
    moduleTitle: null,
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 334,
    seedDownvotes: 38,
    createdAt: "2025-01-07T00:00:00Z",
  },
  {
    id: "real-time-aml-public-reporting",
    title: "Mandate AI-powered real-time anti-money-laundering monitoring with public aggregated reporting",
    description: "Banks must implement real-time transaction monitoring using AI systems certified by regulators. Aggregated AML statistics — suspicious activity volumes by sector, geography, and transaction type — must be published quarterly. Systemic failures in AML attract criminal liability for executives, not just institutional fines.",
    rationale: "An estimated $2tn is laundered through the global financial system annually. Current AML regimes are compliance theatre: banks file Suspicious Activity Reports that overwhelm regulators, while sophisticated layering goes undetected. AI-powered systems can detect patterns invisible to rule-based monitoring. The key reform is executive criminal liability — Deutsche Bank paid $630M in AML fines without a single senior executive prosecution. Fines are a cost of business; prison sentences change behaviour. Public aggregate reporting allows civil society to assess whether banks are genuinely policing their systems.",
    category: "banking",
    moduleSlug: "how-banking-crises-repeat",
    moduleTitle: "Why Banking Crises Keep Happening",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 289,
    seedDownvotes: 41,
    createdAt: "2025-01-08T00:00:00Z",
  },
  {
    id: "debt-jubilee-mechanism",
    title: "Establish a permanent household debt restructuring mechanism for over-indebted individuals",
    description: "Create a statutory debt relief mechanism allowing households whose debt service exceeds 40% of income to apply for restructuring — partial write-down, interest freeze, or extended repayment — without bankruptcy stigma. Funded by a levy on bank profits above a return-on-equity threshold.",
    rationale: "Debt that cannot be repaid will not be repaid — the question is who bears the loss. Currently the answer is always the debtor: garnished wages, lost housing, health damage from financial stress. A debt jubilee mechanism recognises that compound interest on essential debt (student loans, medical bills, emergency credit) can permanently exclude households from economic participation. Iceland's post-2008 household debt restructuring programme was the most successful economic recovery in the developed world — GDP recovered faster than Ireland or Greece, which followed orthodox austerity.",
    category: "banking",
    moduleSlug: "the-savings-and-loan-crisis-of-the-1980s",
    moduleTitle: "The Savings and Loan Crisis of the 1980s",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 356,
    seedDownvotes: 83,
    createdAt: "2025-01-09T00:00:00Z",
  },
  {
    id: "community-reinvestment-mandate",
    title: "Require banks to reinvest proportionally in the communities they take deposits from",
    description: "Any bank taking retail deposits in a region must demonstrate proportional lending back into that region — for housing, small business, and community investment. Annual Community Reinvestment Act-style audits, with results published and tied to licence renewal.",
    rationale: "Commercial banks systematically extract deposits from low-income communities and lend them in wealthier areas with better risk profiles. This accelerates geographic inequality — capital leaves the places that need it most. The US Community Reinvestment Act (1977) established the principle, but enforcement has been weakened. A strengthened, Europe-wide equivalent would require banks to demonstrate geographic reinvestment as a condition of their operating licence — not as a voluntary CSR commitment.",
    category: "banking",
    moduleSlug: "how-wealth-compounds-faster-than-wages",
    moduleTitle: "How wealth compounds faster than wages",
    authorName: "Society Lab",
    isSeeded: true,
    seedUpvotes: 198,
    seedDownvotes: 34,
    createdAt: "2025-01-10T00:00:00Z",
  },
];

export const PROPOSAL_MAP = new Map<string, Proposal>(
  SEEDED_PROPOSALS.map((p) => [p.id, p])
);

export function getProposalById(id: string, userProposals: Proposal[] = []): Proposal | null {
  return PROPOSAL_MAP.get(id) ?? userProposals.find((p) => p.id === id) ?? null;
}

export function getAllProposals(userProposals: Proposal[] = []): Proposal[] {
  return [...SEEDED_PROPOSALS, ...userProposals];
}
