export type QuestionKind = "single" | "multi";

export interface QuizQuestion {
  id: string;
  text: string;
  kind: QuestionKind;
  options: { id: string; text: string }[];
  correct: string[];
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
}

export interface ModuleQuiz {
  moduleSlug: string;
  title: string;
  questions: QuizQuestion[];
}

export const moduleQuizzes: ModuleQuiz[] = [
  {
    moduleSlug: "why-gdp-is-not-the-same-as-wellbeing",
    title: "GDP vs. Wellbeing",
    questions: [
      {
        id: "gdp-1",
        text: "GDP rises when an oil spill occurs and cleanup costs are counted. What does this reveal?",
        kind: "single",
        options: [
          { id: "a", text: "GDP is a reliable proxy for national health" },
          { id: "b", text: "GDP counts economic activity regardless of whether it improves or harms wellbeing" },
          { id: "c", text: "Oil spills are too rare to affect GDP" },
          { id: "d", text: "Cleanup activity always creates net positive welfare" },
        ],
        correct: ["b"],
        explanation: "GDP measures all economic transactions, not their social value. Cleanup spending raises GDP even when it repairs harm. This is the defensive expenditure problem.",
        difficulty: "easy",
      },
      {
        id: "gdp-2",
        text: "Which would REDUCE GDP while potentially increasing wellbeing?",
        kind: "single",
        options: [
          { id: "a", text: "Building a new shopping mall" },
          { id: "b", text: "A parent leaving paid work to care for a child" },
          { id: "c", text: "A new hospital opening" },
          { id: "d", text: "Increased commuting due to urban sprawl" },
        ],
        correct: ["b"],
        explanation: "Unpaid care work is invisible to GDP. When a parent leaves paid employment to raise a child, GDP falls even though real welfare likely rises. This is the care economy blind spot.",
        difficulty: "medium",
      },
      {
        id: "gdp-3",
        text: "The Easterlin Paradox observes that beyond a certain income threshold, more GDP growth does not consistently increase happiness. Why?",
        kind: "single",
        options: [
          { id: "a", text: "People in rich countries are genetically less happy" },
          { id: "b", text: "Relative income and social comparison matter more than absolute income above subsistence" },
          { id: "c", text: "Happiness surveys are unreliable" },
          { id: "d", text: "GDP growth slows automatically at high income levels" },
        ],
        correct: ["b"],
        explanation: "Once basic needs are met, wellbeing is more strongly driven by relative position than absolute wealth. Highly unequal societies often report lower average wellbeing than more equal ones with lower GDP per capita.",
        difficulty: "hard",
      },
      {
        id: "gdp-4",
        text: "Which metrics would best capture what GDP misses? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Median household income" },
          { id: "b", text: "Stock market index" },
          { id: "c", text: "Life expectancy and healthy life years" },
          { id: "d", text: "Hours of unpaid care and voluntary work" },
          { id: "e", text: "Corporate profit margins" },
        ],
        correct: ["a", "c", "d"],
        explanation: "Median income captures distribution. Life expectancy reflects real health outcomes. Unpaid care hours measure social reproduction markets ignore. Stock indices and corporate margins reflect capital returns GDP already captures.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-doughnut-economics-puts-the-economy-inside-limits",
    title: "Doughnut Economics & Green Finance",
    questions: [
      {
        id: "dough-1",
        text: "The core idea of Doughnut economics is that a healthy economy should keep society within:",
        kind: "single",
        options: [
          { id: "a", text: "A social foundation and an ecological ceiling" },
          { id: "b", text: "Balanced budgets and low inflation" },
          { id: "c", text: "Maximum GDP growth and free trade" },
          { id: "d", text: "Private ownership and minimal regulation" },
        ],
        correct: ["a"],
        explanation: "Doughnut economics asks whether everyone is secured above a minimum social floor while total activity stays below ecological ceilings such as climate, biodiversity, and pollution limits.",
        difficulty: "easy",
      },
      {
        id: "dough-2",
        text: "Why does conventional finance often underprice ecological damage?",
        kind: "single",
        options: [
          { id: "a", text: "Banks are legally prohibited from considering environmental data" },
          { id: "b", text: "Many ecological costs are delayed or externalized, while finance rewards shorter-term private returns" },
          { id: "c", text: "Investors prefer poor data quality" },
          { id: "d", text: "Pollution is already fully reflected in all asset prices" },
        ],
        correct: ["b"],
        explanation: "A stable climate, fertile soils, and healthy ecosystems support the whole economy, but their degradation often lands outside the private balance sheet or appears later than the time horizon most assets are priced on.",
        difficulty: "medium",
      },
      {
        id: "dough-3",
        text: "Which policies help integrate ecological limits into the financial system? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Climate stress tests and transition-plan disclosure" },
          { id: "b", text: "Public development banks and retrofit lending" },
          { id: "c", text: "Capital rules or standards that discourage high-pollution assets" },
          { id: "d", text: "Treating ecological risk as irrelevant to loan pricing" },
        ],
        correct: ["a", "b", "c"],
        explanation: "These tools force finance to recognize physical limits and redirect capital. Ignoring ecological risk is precisely the failure the module is describing.",
        difficulty: "medium",
      },
      {
        id: "dough-4",
        text: "A green economy that cuts carbon intensity but leaves people below a social floor still misses what?",
        kind: "single",
        options: [
          { id: "a", text: "The importance of stock market liquidity" },
          { id: "b", text: "The social side of the doughnut: meeting basic needs and sharing transition gains fairly" },
          { id: "c", text: "The need to maximize consumption in every sector" },
          { id: "d", text: "The value of export competitiveness alone" },
        ],
        correct: ["b"],
        explanation: "The doughnut has two boundaries. Ecological sustainability without housing, care, mobility, and energy security is still a failure for human wellbeing.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-pollution-builds-up-until-systems-tip",
    title: "Pollution, Delays & Tipping Points",
    questions: [
      {
        id: "tip-1",
        text: "Why can a pollution problem look manageable for years and then suddenly feel like a crisis?",
        kind: "single",
        options: [
          { id: "a", text: "Because pollution is usually imaginary until media coverage creates panic" },
          { id: "b", text: "Because pollution often accumulates as a stock while visible damage is delayed" },
          { id: "c", text: "Because environmental harm only exists during recessions" },
          { id: "d", text: "Because ecosystems never buffer stress at all" },
        ],
        correct: ["b"],
        explanation: "Many environmental harms build slowly while ecosystems absorb stress for a time. That buffering delays visible damage, which is why institutions often react late.",
        difficulty: "easy",
      },
      {
        id: "tip-2",
        text: "What is a tipping point in a systems sense?",
        kind: "single",
        options: [
          { id: "a", text: "Any year when pollution rises a little above trend" },
          { id: "b", text: "A threshold after which change becomes abrupt, self-reinforcing, or much harder to reverse" },
          { id: "c", text: "A moment when a government announces a new policy target" },
          { id: "d", text: "A temporary drop in public attention to environmental issues" },
        ],
        correct: ["b"],
        explanation: "Tipping points matter because systems do not always change smoothly. Once a threshold is crossed, the same pressure can produce much larger and harder-to-reverse effects.",
        difficulty: "medium",
      },
      {
        id: "tip-3",
        text: "Which indicators matter most if you want to catch ecological overshoot early? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Accumulated pollution stock" },
          { id: "b", text: "Remaining resilience or buffer capacity" },
          { id: "c", text: "Distance to thresholds or tipping risk" },
          { id: "d", text: "Only this year's GDP growth rate" },
        ],
        correct: ["a", "b", "c"],
        explanation: "In systems with delayed feedback, the important signals are stock buildup, resilience, and threshold distance. GDP growth alone tells you almost nothing about whether ecological stability is being quietly undermined.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-lobbying-shapes-policy",
    title: "Lobbying & Policy Capture",
    questions: [
      {
        id: "lob-1",
        text: "The 'revolving door' in politics refers to:",
        kind: "single",
        options: [
          { id: "a", text: "Rapid turnover of elected officials through elections" },
          { id: "b", text: "Movement of people between government regulatory roles and the industries they regulated" },
          { id: "c", text: "Lobbyists physically entering parliament buildings repeatedly" },
          { id: "d", text: "Campaign donation cycles in election years" },
        ],
        correct: ["b"],
        explanation: "The revolving door describes how regulators and legislators move into private sector roles in industries they previously oversaw. This creates structural incentive misalignment: regulators may be lenient knowing future employment depends on industry goodwill.",
        difficulty: "easy",
      },
      {
        id: "lob-2",
        text: "Regulatory capture occurs when:",
        kind: "single",
        options: [
          { id: "a", text: "A government successfully restricts a harmful industry" },
          { id: "b", text: "An industry regulates itself without government interference" },
          { id: "c", text: "The regulated industry gains dominant influence over its own regulator" },
          { id: "d", text: "Citizens elect industry representatives to government" },
        ],
        correct: ["c"],
        explanation: "Regulatory capture is the process by which a regulatory body comes to advance the commercial interests of the industry it regulates, rather than the public interest. It can happen through revolving doors, information asymmetry, or direct lobbying.",
        difficulty: "medium",
      },
      {
        id: "lob-3",
        text: "Which are systemic features that concentrate political influence among wealthy interests? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Legal campaign contribution limits that still allow large bundled donations" },
          { id: "b", text: "Free public education" },
          { id: "c", text: "The high cost of running for office, favouring candidates with wealthy networks" },
          { id: "d", text: "Think tanks funded by industry that produce research aligned with donor interests" },
          { id: "e", text: "Universal suffrage" },
        ],
        correct: ["a", "c", "d"],
        explanation: "These are all legal mechanisms that systematically advantage well-funded interests without constituting outright bribery. Campaign finance loopholes, the cost barrier to candidacy, and industry-funded research that shapes acceptable policy discourse are all structural capture.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-rich-country-corporations-export-corruption",
    title: "Exported Corruption",
    questions: [
      {
        id: "xcor-1",
        text: "What does it mean to say rich countries can 'export corruption'?",
        kind: "single",
        options: [
          { id: "a", text: "Only that poor countries copy rich-country lifestyles" },
          { id: "b", text: "That firms, intermediaries, and financial systems based in richer countries can supply bribes, secrecy, and legal cover for corrupt deals abroad" },
          { id: "c", text: "That all foreign investment is corrupt" },
          { id: "d", text: "That corruption is caused only by international law" },
        ],
        correct: ["b"],
        explanation: "The idea is systemic, not moralistic. Many corrupt deals in poorer countries depend on corporations, banks, brokers, and secrecy tools based in richer ones. The damage is local, but part of the machinery is external.",
        difficulty: "easy",
      },
      {
        id: "xcor-2",
        text: "Why is cross-border corruption hard to punish even when bribery is illegal?",
        kind: "single",
        options: [
          { id: "a", text: "Because host countries always approve the deals openly" },
          { id: "b", text: "Because no country has laws against foreign bribery" },
          { id: "c", text: "Because the scheme can be spread across multiple jurisdictions, intermediaries, and shell companies, raising enforcement friction" },
          { id: "d", text: "Because corporations are immune from prosecution" },
        ],
        correct: ["c"],
        explanation: "Cross-border corruption is often routed through consultants, subsidiaries, shell companies, and bank accounts in different jurisdictions. That fragmentation makes tracing responsibility slow and expensive.",
        difficulty: "medium",
      },
      {
        id: "xcor-3",
        text: "Which actors are often 'professional enablers' of grand corruption? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Lawyers, accountants, and banks that help hide ownership or move funds" },
          { id: "b", text: "Opaque intermediaries and shell-company service providers" },
          { id: "c", text: "Independent journalists exposing the deal" },
          { id: "d", text: "Consultants who structure side agreements outside normal procurement scrutiny" },
        ],
        correct: ["a", "b", "d"],
        explanation: "Enablers do not always pay the bribe directly. They create the legal, financial, and organizational structures that allow illicit payments and hidden ownership to move safely.",
        difficulty: "medium",
      },
      {
        id: "xcor-4",
        text: "What is the main lesson of the Siemens and OPL 245 examples in this module?",
        kind: "single",
        options: [
          { id: "a", text: "Corruption in poor countries is mainly a local cultural issue" },
          { id: "b", text: "A corrupt deal can be organized through powerful foreign corporate networks while the host country absorbs the institutional damage" },
          { id: "c", text: "Foreign companies always improve transparency abroad" },
          { id: "d", text: "Only the oil sector faces corruption risks" },
        ],
        correct: ["b"],
        explanation: "Both examples show that major corruption cases are often transnational systems. The contract, money flows, and legal insulation can sit partly abroad even when the public losses are concentrated in the host country.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-debt-and-megaprojects-create-dependence",
    title: "Debt, Megaprojects & Dependence",
    questions: [
      {
        id: "mega-1",
        text: "A 'white elephant' infrastructure project is best understood as:",
        kind: "single",
        options: [
          { id: "a", text: "Any large project built by a foreign contractor" },
          { id: "b", text: "A project that is prestigious or expensive but delivers poor value relative to its cost and burden" },
          { id: "c", text: "A project that takes more than one year to build" },
          { id: "d", text: "A project in a rural area" },
        ],
        correct: ["b"],
        explanation: "The key issue is not just size. A white elephant is a project whose real social value is weak compared with the debt, cost, maintenance burden, or opportunity cost it creates.",
        difficulty: "easy",
      },
      {
        id: "mega-2",
        text: "Why are large infrastructure projects especially vulnerable to corruption?",
        kind: "single",
        options: [
          { id: "a", text: "Because engineering is always corrupt" },
          { id: "b", text: "Because they are large, technically complex, and capital-intensive, making costs and forecasts easier to manipulate" },
          { id: "c", text: "Because citizens prefer smaller projects" },
          { id: "d", text: "Because they never require public borrowing" },
        ],
        correct: ["b"],
        explanation: "Megaprojects combine high budgets, technical opacity, and political symbolism. That mix makes it easier to hide overpricing, tied procurement, kickbacks, and unrealistic demand projections.",
        difficulty: "medium",
      },
      {
        id: "mega-3",
        text: "Which indicators better test whether a project fits a country's real development path? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Independent feasibility and demand analysis" },
          { id: "b", text: "Debt service burden over time" },
          { id: "c", text: "Expected utilization and maintenance costs" },
          { id: "d", text: "Whether the project looks impressive on opening day" },
        ],
        correct: ["a", "b", "c"],
        explanation: "The problem is not whether leaders can stage a launch. It is whether the project meets a real need, remains financially sustainable, and can be operated and maintained without crowding out other priorities.",
        difficulty: "medium",
      },
      {
        id: "mega-4",
        text: "What do the Montenegro highway and Sampur plant examples mainly illustrate?",
        kind: "single",
        options: [
          { id: "a", text: "That all infrastructure borrowing should stop" },
          { id: "b", text: "That poorly planned or opaque projects can lock the public into long-term costs even when the value case is weak" },
          { id: "c", text: "That energy and transport planning should be separated completely" },
          { id: "d", text: "That only democratic countries face corruption risks" },
        ],
        correct: ["b"],
        explanation: "Both examples show the delayed structure of harm: the political moment is short, but the debt, losses, and squeezed fiscal space can last for years or decades.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "why-cities-create-stress-or-freedom",
    title: "Cities & Everyday Life",
    questions: [
      {
        id: "city-1",
        text: "What does '15-minute city' design aim to achieve?",
        kind: "single",
        options: [
          { id: "a", text: "Faster road networks reducing commute times to 15 minutes" },
          { id: "b", text: "Urban design where daily needs are accessible within 15 minutes on foot or bike" },
          { id: "c", text: "Mandatory working-from-home policies" },
          { id: "d", text: "Restricting city size to 15km radius" },
        ],
        correct: ["b"],
        explanation: "The 15-minute city concept argues cities should be designed so residents can meet all daily needs within a 15-minute walk or bike ride, reducing car dependence, commuting stress, and carbon emissions while building local community.",
        difficulty: "easy",
      },
      {
        id: "city-2",
        text: "Why do car-centric urban designs tend to worsen inequality over time?",
        kind: "single",
        options: [
          { id: "a", text: "Cars are luxury goods unavailable to low-income residents" },
          { id: "b", text: "Car infrastructure diverts investment from public transit, making car ownership a prerequisite for jobs, which burdens low-income households most" },
          { id: "c", text: "Traffic jams exclusively affect wealthy neighbourhoods" },
          { id: "d", text: "Parking spaces reduce available housing in rich areas only" },
        ],
        correct: ["b"],
        explanation: "Car-centric design creates a vicious cycle: public transit is defunded, forcing households to own cars to access jobs, which consumes 15-20% of low-income budgets vs 5% for high-income households.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-media-incentives-produce-outrage",
    title: "Media Incentives & Outrage",
    questions: [
      {
        id: "med-1",
        text: "Attention economy business models optimise primarily for:",
        kind: "single",
        options: [
          { id: "a", text: "User satisfaction and accurate information" },
          { id: "b", text: "Engagement time and emotional arousal regardless of content quality" },
          { id: "c", text: "Subscriber revenue tied to renewal" },
          { id: "d", text: "Advertiser brand safety" },
        ],
        correct: ["b"],
        explanation: "Advertising-funded platforms maximise time-on-platform. Emotionally negative or outrage-inducing content generates higher engagement, so the algorithm surfaces it more regardless of accuracy.",
        difficulty: "easy",
      },
      {
        id: "med-2",
        text: "A 'steelman' argument means:",
        kind: "single",
        options: [
          { id: "a", text: "Exaggerating the weakest version of an opposing argument to defeat it easily" },
          { id: "b", text: "Constructing the strongest, most charitable version of the opposing argument before responding" },
          { id: "c", text: "Finding corporate lobbying behind an opposing view" },
          { id: "d", text: "Presenting both sides as equally valid regardless of evidence" },
        ],
        correct: ["b"],
        explanation: "Steelmanning presents the strongest possible version of an opposing view. It prevents the cognitive cheap win of defeating a distortion of what the other side actually believes, and produces better arguments on all sides.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "why-housing-becomes-financialized",
    title: "Housing Financialization",
    questions: [
      {
        id: "hous-1",
        text: "Housing 'financialization' means:",
        kind: "single",
        options: [
          { id: "a", text: "Mortgages becoming available to more buyers" },
          { id: "b", text: "The transformation of housing from shelter into an investment asset traded for returns" },
          { id: "c", text: "Government construction of social housing" },
          { id: "d", text: "Tax relief for homeowners" },
        ],
        correct: ["b"],
        explanation: "Financialization means homes increasingly function as stores of value and investment vehicles. When housing is primarily an asset, owners benefit from price rises while renters are priced out — creating a structural conflict of interest between existing homeowners and would-be homeowners.",
        difficulty: "easy",
      },
      {
        id: "hous-2",
        text: "Why does increasing housing supply sometimes fail to reduce prices in financialized markets?",
        kind: "single",
        options: [
          { id: "a", text: "Construction companies are always too slow to respond" },
          { id: "b", text: "New supply is often absorbed by investors seeking yield rather than increasing homes available for residence" },
          { id: "c", text: "New housing always has higher quality that justifies higher prices" },
          { id: "d", text: "Zoning laws prevent construction near job centres" },
        ],
        correct: ["b"],
        explanation: "In financialized markets, new units can be bought off-plan by investors as yield-bearing assets, never entering the owner-occupier or affordable rental market. Supply without demand-side reform may simply add more investment inventory rather than more homes.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-corruption-behaves-like-a-hidden-tax",
    title: "Corruption as Hidden Tax",
    questions: [
      {
        id: "corr-1",
        text: "Why does corruption function like a tax even when no money changes hands directly?",
        kind: "single",
        options: [
          { id: "a", text: "It doesn't — only financial transactions constitute corruption" },
          { id: "b", text: "Delays, connections, and informal requirements all impose real costs and uncertainty" },
          { id: "c", text: "Corruption is always cheaper than formal taxes" },
          { id: "d", text: "Governments classify bribes as tax revenue" },
        ],
        correct: ["b"],
        explanation: "Corruption imposes costs through multiple channels beyond direct payments: time lost navigating gatekeepers, uncertainty about outcomes, investment in connections, and chilling effects on those who can't pay.",
        difficulty: "medium",
      },
      {
        id: "corr-2",
        text: "What makes corruption self-reinforcing at the systemic level? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "When corruption is expected, honest actors are disadvantaged relative to those who pay" },
          { id: "b", text: "Corrupt officials invest in maintaining the systems that produce corruption income" },
          { id: "c", text: "Transparency always increases corruption" },
          { id: "d", text: "Citizens who observe corruption reduce their own compliance with rules and taxes" },
        ],
        correct: ["a", "b", "d"],
        explanation: "Corruption creates reinforcing loops: honest actors lose competitive ground (a), profiteers have incentives to protect the system (b), and witnessing corruption reduces public trust and tax compliance broadly (d).",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-capitalism-socialism-and-communism-differ",
    title: "Capitalism, Socialism & Communism",
    questions: [
      {
        id: "ideology-1",
        text: "Which question most directly separates capitalism from socialism at the level of system design?",
        kind: "single",
        options: [
          { id: "a", text: "Whether a country has taxes" },
          { id: "b", text: "Who owns or controls major productive assets and investment decisions" },
          { id: "c", text: "Whether people are allowed to vote" },
          { id: "d", text: "Whether prices ever change" },
        ],
        correct: ["b"],
        explanation: "The central comparison is ownership and control: who owns productive assets, who decides where investment goes, and who captures the surplus. Taxes, elections, and price changes matter, but they do not by themselves define the system.",
        difficulty: "easy",
      },
      {
        id: "ideology-2",
        text: "Why are the Nordic countries not good examples of 'pure socialism'?",
        kind: "single",
        options: [
          { id: "a", text: "Because they have no public services" },
          { id: "b", text: "Because they combine capitalist markets and private firms with strong welfare states, unions, and public provision" },
          { id: "c", text: "Because socialism can only exist in poor countries" },
          { id: "d", text: "Because they do not regulate banks" },
        ],
        correct: ["b"],
        explanation: "Nordic systems are mixed economies. Markets and private ownership remain central, but they are combined with stronger public services, taxation, labor institutions, and redistribution than in more market-liberal capitalist systems.",
        difficulty: "medium",
      },
      {
        id: "ideology-3",
        text: "In Marx's theoretical sense, communism refers to:",
        kind: "single",
        options: [
          { id: "a", text: "Any economy with large welfare benefits" },
          { id: "b", text: "A classless society with common ownership where the state is no longer needed as a coercive power" },
          { id: "c", text: "Any country with a ruling communist party" },
          { id: "d", text: "A market economy with high corporate taxes" },
        ],
        correct: ["b"],
        explanation: "In Marxist theory, communism is the end state beyond class rule and beyond the need for a coercive state. Historical communist regimes usually described themselves as transitional states, not as the final stateless end condition.",
        difficulty: "hard",
      },
      {
        id: "ideology-4",
        text: "Which arrangements could fit within a socialist model? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Worker-owned cooperatives competing in markets" },
          { id: "b", text: "Public ownership of key utilities or infrastructure" },
          { id: "c", text: "Social wealth funds that hold assets on behalf of citizens" },
          { id: "d", text: "A system where ownership and investment are controlled only by private shareholders" },
        ],
        correct: ["a", "b", "c"],
        explanation: "Socialism is a family of designs, not one blueprint. It can include cooperatives, public ownership, municipal ownership, and social funds. A system controlled only by private shareholders is closer to capitalism.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-the-eu-makes-decisions",
    title: "How the EU Makes Decisions",
    questions: [
      {
        id: "eu-1",
        text: "In the EU's ordinary legislative procedure, who normally has equal say over the final law?",
        kind: "single",
        options: [
          { id: "a", text: "The European Commission and the European Central Bank" },
          { id: "b", text: "The European Parliament and the Council of the European Union" },
          { id: "c", text: "The European Council and the Court of Justice" },
          { id: "d", text: "National parliaments and the Commission" },
        ],
        correct: ["b"],
        explanation: "Under the ordinary legislative procedure, the Commission proposes legislation, but the European Parliament and the Council of the EU must agree on the text for it to become law.",
        difficulty: "easy",
      },
      {
        id: "eu-2",
        text: "What is the key difference between the European Council and the Council of the European Union?",
        kind: "single",
        options: [
          { id: "a", text: "The European Council sets broad political direction, while the Council of the EU negotiates and adopts laws with Parliament" },
          { id: "b", text: "The European Council is directly elected, while the Council of the EU is appointed by the Commission" },
          { id: "c", text: "The Council of the EU interprets law, while the European Council enforces it" },
          { id: "d", text: "There is no real difference; they are two names for the same institution" },
        ],
        correct: ["a"],
        explanation: "The European Council is the summit of heads of state or government that sets broad priorities. The Council of the EU is the ministerial institution that negotiates and adopts laws, usually alongside Parliament.",
        difficulty: "medium",
      },
      {
        id: "eu-3",
        text: "What is the role of national parliaments in shared-competence areas of EU lawmaking?",
        kind: "single",
        options: [
          { id: "a", text: "They directly veto every EU law" },
          { id: "b", text: "They choose the President of the European Commission" },
          { id: "c", text: "They can review proposals for subsidiarity and issue opinions if they think action should stay closer to national or regional level" },
          { id: "d", text: "They sit as a third chamber inside the European Parliament" },
        ],
        correct: ["c"],
        explanation: "National parliaments receive proposals and can object on subsidiarity grounds when they think action would be more effective below the EU level. This is part of the subsidiarity control mechanism.",
        difficulty: "medium",
      },
      {
        id: "eu-4",
        text: "Which features make EU decision-making more negotiated than a typical single-state parliament? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "There are 27 member-state governments represented in the Council" },
          { id: "b", text: "The Parliament and Council usually both have to agree on the text" },
          { id: "c", text: "Some important areas use special procedures or unanimity" },
          { id: "d", text: "The Commission is the only institution that can vote on laws" },
        ],
        correct: ["a", "b", "c"],
        explanation: "The EU is negotiated because multiple institutions and member governments must often agree. The Commission usually proposes legislation, but it does not by itself vote laws into force.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-the-us-government-makes-decisions",
    title: "How the U.S. Government Makes Decisions",
    questions: [
      {
        id: "usgov-1",
        text: "For a normal federal bill to become law, which institutions must usually approve the same text?",
        kind: "single",
        options: [
          { id: "a", text: "The House, the Senate, and the President" },
          { id: "b", text: "The House, the Supreme Court, and the President" },
          { id: "c", text: "The Senate alone" },
          { id: "d", text: "The President and state governors" },
        ],
        correct: ["a"],
        explanation: "In the usual path, the House and Senate must pass the same bill text and send it to the President, who signs or vetoes it. Congress can override a veto only with two-thirds in both chambers.",
        difficulty: "easy",
      },
      {
        id: "usgov-2",
        text: "Which comparison between the House and Senate is correct?",
        kind: "single",
        options: [
          { id: "a", text: "Both chambers represent states equally" },
          { id: "b", text: "The House is population-based with 435 voting members, while the Senate has 100 members with two per state" },
          { id: "c", text: "The Senate is population-based, while the House gives each state two members" },
          { id: "d", text: "Only the Senate can introduce bills" },
        ],
        correct: ["b"],
        explanation: "The House is apportioned by population and capped at 435 voting representatives. The Senate gives every state equal representation with two senators each, for a total of 100.",
        difficulty: "easy",
      },
      {
        id: "usgov-3",
        text: "What is the filibuster most closely associated with in modern U.S. governance?",
        kind: "single",
        options: [
          { id: "a", text: "A House rule allowing governors to block bills" },
          { id: "b", text: "A Senate procedure that can force a supermajority to end debate on many measures" },
          { id: "c", text: "A Supreme Court doctrine for striking down laws" },
          { id: "d", text: "A constitutional rule requiring unanimous state approval of budgets" },
        ],
        correct: ["b"],
        explanation: "The filibuster is associated with the Senate, where ending debate on many measures often requires cloture. That makes Senate procedure a major veto point beyond simple majority voting.",
        difficulty: "medium",
      },
      {
        id: "usgov-4",
        text: "Which are major veto points in the U.S. federal system? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Committee gatekeeping in Congress" },
          { id: "b", text: "Senate procedural hurdles and bicameral disagreement" },
          { id: "c", text: "Presidential veto power" },
          { id: "d", text: "Judicial review after implementation" },
        ],
        correct: ["a", "b", "c", "d"],
        explanation: "The U.S. system has many veto points. Bills can stall in committee, die between House and Senate, be vetoed by the President, or later be narrowed or invalidated through judicial review.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-banking-crises-repeat",
    title: "Banking Crises: Why They Keep Happening",
    questions: [
      {
        id: "bkcrisis-1",
        text: "A bank run is described as 'self-fulfilling' because:",
        kind: "single",
        options: [
          { id: "a", text: "Banks always make poor lending decisions" },
          { id: "b", text: "The fear that others will withdraw makes withdrawal rational, turning belief into reality" },
          { id: "c", text: "Central banks deliberately cause panics to reset the system" },
          { id: "d", text: "Depositors have insider information about losses" },
        ],
        correct: ["b"],
        explanation: "A solvent bank can be destroyed purely by panic. If enough depositors believe others will withdraw, it becomes individually rational to withdraw first — even with no underlying problem. This is the coordination failure at the heart of bank runs.",
        difficulty: "medium",
      },
      {
        id: "bkcrisis-2",
        text: "Deposit insurance stops bank runs primarily by:",
        kind: "single",
        options: [
          { id: "a", text: "Making banks more profitable so they can absorb losses" },
          { id: "b", text: "Removing the incentive to be first in line — if deposits are guaranteed, there is nothing to gain by rushing" },
          { id: "c", text: "Requiring banks to hold 100% reserves" },
          { id: "d", text: "Giving the government ownership of all deposits" },
        ],
        correct: ["b"],
        explanation: "Deposit insurance eliminates the first-mover advantage. If your deposit is guaranteed regardless of what others do, there is no reason to queue outside the branch — which breaks the panic loop before it starts.",
        difficulty: "easy",
      },
      {
        id: "bkcrisis-3",
        text: "The shadow banking sector caused the 2008 crisis to be so severe because:",
        kind: "single",
        options: [
          { id: "a", text: "Shadow banks were publicly owned and politically protected" },
          { id: "b", text: "It operated with bank-like leverage and maturity mismatch but without deposit insurance or regulatory capital requirements" },
          { id: "c", text: "Shadow banks held only government bonds" },
          { id: "d", text: "It was too small to matter until it suddenly collapsed" },
        ],
        correct: ["b"],
        explanation: "Shadow banking (money market funds, repo markets, investment banks, conduits) replicated the economic function of banking — borrowing short, lending long, at high leverage — without the safety net that makes regulated banking more stable.",
        difficulty: "hard",
      },
      {
        id: "bkcrisis-4",
        text: "What does 'lender of last resort' mean in a banking crisis?",
        kind: "single",
        options: [
          { id: "a", text: "The bank that makes the riskiest loans in normal times" },
          { id: "b", text: "A central bank willing to lend freely to solvent banks against good collateral during a panic" },
          { id: "c", text: "The IMF bailing out insolvent governments" },
          { id: "d", text: "Private investors who buy distressed bank assets" },
        ],
        correct: ["b"],
        explanation: "Bagehot's 19th-century principle: in a panic, a central bank should lend freely at a penalty rate to banks that are solvent but illiquid. This provides breathing room, preventing contagion from turning a solvency rumour into an actual insolvency.",
        difficulty: "medium",
      },
      {
        id: "bkcrisis-5",
        text: "Which patterns appear across all major banking crises from 1907 to 2023? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "A period of stability breeding complacency and deregulation" },
          { id: "b", text: "Institutions operating with bank-like risk outside the regulatory perimeter" },
          { id: "c", text: "Contagion spreading through interconnected balance sheets" },
          { id: "d", text: "Crises always caused by foreign currency debt" },
          { id: "e", text: "Regulatory memory fading as the last crisis recedes" },
        ],
        correct: ["a", "b", "c", "e"],
        explanation: "These four dynamics — stability-induced complacency, regulatory gap exploitation, contagion, and generational forgetting — recur whether the trigger is trust companies in 1907, S&Ls in the 1980s, or concentrated uninsured deposits in 2023. Foreign currency mismatches are a specific EM-market variant, not universal.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-banks-create-money",
    title: "How Banks Create Money",
    questions: [
      {
        id: "mon-1",
        text: "When a commercial bank issues a mortgage loan of £200,000, what actually happens?",
        kind: "single",
        options: [
          { id: "a", text: "The bank transfers £200,000 from its reserves to the borrower" },
          { id: "b", text: "The bank borrows £200,000 from the central bank and passes it on" },
          { id: "c", text: "The bank creates a new £200,000 deposit and matching debt simultaneously — new money from an accounting entry" },
          { id: "d", text: "The bank moves deposits from other customers to the borrower" },
        ],
        correct: ["c"],
        explanation: "Money creation through lending is an accounting act. The bank creates two entries simultaneously: a new deposit (liability) and a new loan asset. No pre-existing money is moved. The Bank of England confirmed this in its 2014 quarterly bulletin.",
        difficulty: "medium",
      },
      {
        id: "mon-2",
        text: "Since commercial banks create most money through lending, what determines where new money flows?",
        kind: "single",
        options: [
          { id: "a", text: "Central bank mandates about productive investment" },
          { id: "b", text: "Democratic votes on investment priorities" },
          { id: "c", text: "Private banks acting on profit signals" },
          { id: "d", text: "International agreements coordinating global investment" },
        ],
        correct: ["c"],
        explanation: "Most money in modern economies is created by commercial banks when they make loans. Banks lend to whoever offers the best risk-adjusted return — which in practice means mortgages and financial assets rather than productive investment. No democratic or policy mandate shapes this allocation by default.",
        difficulty: "hard",
      },
    ],
  },

  {
    moduleSlug: "how-the-2008-financial-crisis-happened",
    title: "The 2008 Financial Crisis",
    questions: [
      {
        id: "fc08-1",
        text: "What is a collateralised debt obligation (CDO) and why did it concentrate rather than disperse risk?",
        kind: "single",
        options: [
          { id: "a", text: "A government bond backed by tax revenue, which disperses risk across all taxpayers" },
          { id: "b", text: "A security built from tranches of mortgage pools — when all mortgages correlated in a national downturn, the assumed diversification disappeared" },
          { id: "c", text: "A central bank facility for emergency lending, which disperses risk to the public sector" },
          { id: "d", text: "A derivative contract between two banks with no connection to the housing market" },
        ],
        correct: ["b"],
        explanation: "CDOs were modelled on the assumption that regional house prices were uncorrelated. When the entire US housing market fell together, the default correlation collapsed the diversification argument — senior tranches rated AAA failed alongside the equity tranche.",
        difficulty: "hard",
      },
      {
        id: "fc08-2",
        text: "The 'originate-to-distribute' model created a systemic problem because:",
        kind: "single",
        options: [
          { id: "a", text: "It prevented banks from making enough mortgages to meet demand" },
          { id: "b", text: "Originators earned fees upfront and sold the loan on, so they had no incentive to ensure it could be repaid" },
          { id: "c", text: "It required all mortgages to meet strict government quality standards" },
          { id: "d", text: "It made the secondary market too liquid and efficient" },
        ],
        correct: ["b"],
        explanation: "When the party originating a loan immediately sells it, they capture the fee and pass the risk. This severs the link between incentive and outcome — the originators of NINJA (no income, no job, no assets) loans were paid regardless of whether borrowers defaulted.",
        difficulty: "medium",
      },
      {
        id: "fc08-3",
        text: "The TED spread and LIBOR-OIS spread spiked in 2007-2008. What were these signals indicating?",
        kind: "single",
        options: [
          { id: "a", text: "That house prices were rising faster than wages" },
          { id: "b", text: "That banks had stopped trusting each other in interbank lending markets — a sign of systemic counterparty fear" },
          { id: "c", text: "That the Federal Reserve was raising interest rates" },
          { id: "d", text: "That foreign banks were withdrawing dollar deposits" },
        ],
        correct: ["b"],
        explanation: "The TED spread (T-bill vs Eurodollar) and LIBOR-OIS spread measure the premium banks charge each other above risk-free rates. Spikes signal that banks fear their counterparts may be insolvent — interbank credit freezes, and the real economy loses access to short-term funding.",
        difficulty: "hard",
      },
      {
        id: "fc08-4",
        text: "Which features made shadow banking fragile in a way that regulated banking was not? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Funded by short-term wholesale debt that could be withdrawn overnight (repo, commercial paper)" },
          { id: "b", text: "No deposit insurance to prevent runs on funding" },
          { id: "c", text: "No lender of last resort with a formal mandate to provide liquidity" },
          { id: "d", text: "Subject to the same capital requirements as commercial banks" },
        ],
        correct: ["a", "b", "c"],
        explanation: "Shadow banks performed economic banking functions (borrowing short, lending long) without the stabilizers: deposit insurance eliminates panic incentives, lender of last resort provides liquidity in a crisis, and capital requirements limit leverage. Shadow banking had none of these.",
        difficulty: "hard",
      },
      {
        id: "fc08-5",
        text: "What was the core reason AIG required a $182bn government rescue?",
        kind: "single",
        options: [
          { id: "a", text: "AIG had made large direct investments in subprime mortgages" },
          { id: "b", text: "AIG had sold credit default swaps guaranteeing CDO performance without holding adequate capital to pay if they defaulted" },
          { id: "c", text: "AIG was a commercial bank that had lent to homeowners directly" },
          { id: "d", text: "AIG's insurance subsidiaries had invested in Lehman Brothers bonds" },
        ],
        correct: ["b"],
        explanation: "AIG's Financial Products division sold protection on CDOs to banks worldwide — effectively acting as an insurer but without the actuarial reserves required of actual insurance. When CDOs defaulted en masse, AIG owed payments it could not make, threatening every bank that had bought protection from it.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "the-savings-and-loan-crisis-of-the-1980s",
    title: "The Savings & Loan Crisis",
    questions: [
      {
        id: "sl-1",
        text: "What is 'duration mismatch' and why was it fatal to savings and loans in the early 1980s?",
        kind: "single",
        options: [
          { id: "a", text: "Thrifts held assets and liabilities with matching maturities, creating a stable but low-yield business" },
          { id: "b", text: "Thrifts funded 30-year fixed-rate mortgages with short-term deposits that repriced at market rates — when rates rose, deposit costs soared while asset yields were locked" },
          { id: "c", text: "S&Ls lent short-term but borrowed long-term, creating cash-flow problems" },
          { id: "d", text: "Duration mismatch refers to the difference between management tenure and loan terms" },
        ],
        correct: ["b"],
        explanation: "The classic S&L mismatch: they borrowed at floating short-term rates (deposits) and lent at fixed long-term rates (30-year mortgages). When Volcker raised rates to 20%, deposit costs exceeded mortgage yields — the industry was collectively insolvent by any honest accounting.",
        difficulty: "medium",
      },
      {
        id: "sl-2",
        text: "Regulatory forbearance in the S&L crisis means regulators chose to:",
        kind: "single",
        options: [
          { id: "a", text: "Close insolvent institutions quickly to minimise losses" },
          { id: "b", text: "Allow insolvent institutions to keep operating and report losses as assets, hoping they would grow back to solvency" },
          { id: "c", text: "Nationalise all failing thrifts and run them as public utilities" },
          { id: "d", text: "Raise deposit insurance premiums to reflect increased risk" },
        ],
        correct: ["b"],
        explanation: "Forbearance means delaying recognition of insolvency. Regulators allowed technically insolvent thrifts to continue operating, recognising losses as assets on 'regulatory accounting principles' rather than real values. This delayed the crisis while allowing losses to compound.",
        difficulty: "medium",
      },
      {
        id: "sl-3",
        text: "Why did deregulation (Garn-St Germain Act, 1982) make the crisis worse rather than helping thrifts recover?",
        kind: "single",
        options: [
          { id: "a", text: "It removed the federal deposit insurance guarantee from thrift deposits" },
          { id: "b", text: "It allowed insolvent, deposit-insured institutions to invest in junk bonds and commercial real estate — creating a heads-I-win, tails-taxpayer-loses gamble" },
          { id: "c", text: "It forced thrifts to hold more government bonds, reducing their returns" },
          { id: "d", text: "It merged thrifts with commercial banks, removing their home-lending focus" },
        ],
        correct: ["b"],
        explanation: "Expanding investment powers for entities with federally guaranteed deposits and no new capital requirements created severe moral hazard. Insolvent thrifts had nothing to lose by gambling: if the bet paid off, they survived; if it failed, the FSLIC (ultimately taxpayers) absorbed the additional loss.",
        difficulty: "hard",
      },
      {
        id: "sl-4",
        text: "What pattern do the S&L crisis and later crises (2008, SVB 2023) share regarding regulatory response? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Initial regulatory forbearance that delays recognition and amplifies eventual losses" },
          { id: "b", text: "Institutions operating in areas where deposit-like funding was not matched by deposit-like regulation" },
          { id: "c", text: "Rapid decisive intervention that contained losses before they spread" },
          { id: "d", text: "Political pressure protecting well-connected institutions from enforcement" },
        ],
        correct: ["a", "b", "d"],
        explanation: "All three crises show delayed recognition (a), regulatory perimeter gaps where risk was taken without safety net constraints (b), and political interference (d — Keating Five in S&L, Greenspan-era deference in 2008, lobbying against Dodd-Frank in SVB's case). Rapid decisive intervention is the lesson learned, not the pattern that occurred.",
        difficulty: "hard",
      },
    ],
  },
  {
    moduleSlug: "how-print-era-movements-turned-ideas-into-power",
    title: "Print-Era Social Movements",
    questions: [
      {
        id: "printmov-1",
        text: "What made print-era movements different from many earlier local revolts?",
        kind: "single",
        options: [
          { id: "a", text: "They were the first movements with any moral language" },
          { id: "b", text: "They could cheaply copy, translate, and circulate arguments across many communities" },
          { id: "c", text: "They no longer faced censorship or repression" },
          { id: "d", text: "They relied mainly on radio and telegraphy" },
        ],
        correct: ["b"],
        explanation: "The key shift was lower communication cost. Pamphlets, broadsides, petitions, and vernacular texts let grievances travel and repeat across towns, congregations, and trading networks.",
        difficulty: "easy",
      },
      {
        id: "printmov-2",
        text: "Why were elite defections often important to early mass movements?",
        kind: "single",
        options: [
          { id: "a", text: "Without them, ordinary people had no grievances" },
          { id: "b", text: "They reduced the need for any local organizing" },
          { id: "c", text: "They could provide protection, printing capacity, money, or legitimacy against repression" },
          { id: "d", text: "They guaranteed movements would stay peaceful" },
        ],
        correct: ["c"],
        explanation: "Printers, merchants, nobles, clergy, and officials sometimes gave movements enough shelter to survive censorship and scale beyond a local outbreak.",
        difficulty: "medium",
      },
      {
        id: "printmov-3",
        text: "Which tactics are most typical of print-era mass politics? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Pamphlets and broadsides" },
          { id: "b", text: "Petitions and signature campaigns" },
          { id: "c", text: "Livestreamed police encounters" },
          { id: "d", text: "Vernacular sermons and testimony" },
        ],
        correct: ["a", "b", "d"],
        explanation: "Print-era mobilization depended on copied texts, petitions, sermons, testimonies, and translated arguments. Livestreaming belongs to digital-networked movements centuries later.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-industrial-mass-movements-won-rights",
    title: "Industrial Mass Movements",
    questions: [
      {
        id: "indmov-1",
        text: "Why did industrialization help create mass labor and suffrage movements?",
        kind: "single",
        options: [
          { id: "a", text: "Factories and cities concentrated people facing similar risks and exclusions" },
          { id: "b", text: "Industrial states immediately granted universal rights" },
          { id: "c", text: "Railways made repression impossible" },
          { id: "d", text: "Newspapers replaced the need for organizations" },
        ],
        correct: ["a"],
        explanation: "Industrial society clustered people in workplaces and cities, making repeated organizing easier and turning shared hardship into shared political identity.",
        difficulty: "easy",
      },
      {
        id: "indmov-2",
        text: "What usually made industrial movements durable rather than one-off protests?",
        kind: "single",
        options: [
          { id: "a", text: "A single dramatic speech" },
          { id: "b", text: "Stable organizations such as unions, dues networks, newspapers, and committees" },
          { id: "c", text: "Relying only on spontaneous crowds" },
          { id: "d", text: "Avoiding any economic disruption" },
        ],
        correct: ["b"],
        explanation: "Mass organizations allowed movements to survive defeat, coordinate across regions, and come back stronger after failed strikes or petitions.",
        difficulty: "medium",
      },
      {
        id: "indmov-3",
        text: "Which reforms are strongly associated with industrial-era mass movements? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Expanded suffrage" },
          { id: "b", text: "Labor protections around hours and safety" },
          { id: "c", text: "The invention of the internet" },
          { id: "d", text: "Growth of mass parties and unions" },
        ],
        correct: ["a", "b", "d"],
        explanation: "Industrial movements helped drive labor law, wider voting rights, union recognition, and mass membership politics. They did not invent digital technologies.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-anti-colonial-movements-dismantled-empires",
    title: "Anti-Colonial Movements",
    questions: [
      {
        id: "anticol-1",
        text: "Which combination most often helped anti-colonial movements succeed?",
        kind: "single",
        options: [
          { id: "a", text: "Only symbolic nationalism with no mass participation" },
          { id: "b", text: "Mass organization, imperial weakness, and a credible claim to self-determination" },
          { id: "c", text: "Purely economic growth inside the colony" },
          { id: "d", text: "A total absence of international politics" },
        ],
        correct: ["b"],
        explanation: "Anti-colonial movements broke through when broad grievance was organized nationally and empires were too weak, costly, or illegitimate to maintain rule.",
        difficulty: "easy",
      },
      {
        id: "anticol-2",
        text: "Why did formal independence not automatically end domination?",
        kind: "single",
        options: [
          { id: "a", text: "New states were always immediately stronger than empires" },
          { id: "b", text: "Colonial borders, debt, export dependence, and inherited institutions often remained" },
          { id: "c", text: "Anti-colonial leaders never wanted sovereignty" },
          { id: "d", text: "The United Nations prohibited full independence" },
        ],
        correct: ["b"],
        explanation: "Political sovereignty was a huge turning point, but many postcolonial states still faced structures built under empire, including unequal trade patterns and weak or coercive inherited institutions.",
        difficulty: "medium",
      },
      {
        id: "anticol-3",
        text: "Which were common anti-colonial movement tools? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Boycotts and strikes" },
          { id: "b", text: "National parties, schools, and newspapers" },
          { id: "c", text: "Claims framed around self-determination" },
          { id: "d", text: "Exclusive reliance on platform algorithms" },
        ],
        correct: ["a", "b", "c"],
        explanation: "Anti-colonial struggles used organizational infrastructure, political claims to self-rule, and many forms of direct action. Platform algorithms belong to a much later era.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-rights-based-movements-expand-citizenship",
    title: "Rights-Based Movements",
    questions: [
      {
        id: "rights-1",
        text: "What is the core contradiction rights-based movements usually expose?",
        kind: "single",
        options: [
          { id: "a", text: "Societies have no ideals at all" },
          { id: "b", text: "A society claims equal rights or dignity while excluding some people in practice" },
          { id: "c", text: "Every institution is secretly anti-technology" },
          { id: "d", text: "Only economic issues matter in politics" },
        ],
        correct: ["b"],
        explanation: "These movements gain force by making visible the gap between universal promises and unequal lived reality.",
        difficulty: "easy",
      },
      {
        id: "rights-2",
        text: "Why is institutional follow-through so important after dramatic protests?",
        kind: "single",
        options: [
          { id: "a", text: "Because public attention automatically writes legislation" },
          { id: "b", text: "Because without legal, administrative, or budget changes, moral victories can remain symbolic" },
          { id: "c", text: "Because movements should avoid coalition-building" },
          { id: "d", text: "Because repression always disappears after one march" },
        ],
        correct: ["b"],
        explanation: "Rights-based victories last when protest is converted into enforceable changes through courts, legislatures, agencies, budgets, and design standards.",
        difficulty: "medium",
      },
      {
        id: "rights-3",
        text: "Which features commonly strengthen rights-based movements? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Visible injustice that bystanders can no longer deny" },
          { id: "b", text: "Broad coalitions beyond the directly affected group" },
          { id: "c", text: "Legal and policy strategy alongside protest" },
          { id: "d", text: "Keeping exclusion hidden from the public" },
        ],
        correct: ["a", "b", "c"],
        explanation: "Visibility, coalition breadth, and institutional strategy are recurring success conditions. Hidden harm makes mobilization harder, not easier.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-networked-digital-movements-scale",
    title: "Networked Digital Movements",
    questions: [
      {
        id: "digitalmov-1",
        text: "What is the biggest structural advantage of networked digital movements?",
        kind: "single",
        options: [
          { id: "a", text: "They eliminate the need for offline action" },
          { id: "b", text: "They can document events and recruit participants at very low coordination cost" },
          { id: "c", text: "They are immune to fragmentation" },
          { id: "d", text: "They automatically control formal institutions" },
        ],
        correct: ["b"],
        explanation: "Phones, platforms, and hashtags let movements witness events quickly and lower the threshold for recognition, sharing, donation, and turnout.",
        difficulty: "easy",
      },
      {
        id: "digitalmov-2",
        text: "What is a common weakness of digital-networked movements?",
        kind: "single",
        options: [
          { id: "a", text: "They always have too much hierarchy" },
          { id: "b", text: "Virality can outrun the organizations needed for durable policy change" },
          { id: "c", text: "They cannot influence public language" },
          { id: "d", text: "They never leave social media platforms" },
        ],
        correct: ["b"],
        explanation: "Attention can arrive faster than strategy, negotiation capacity, or institutional depth. That mismatch is one of the signature problems of digital-era mobilization.",
        difficulty: "medium",
      },
      {
        id: "digitalmov-3",
        text: "Which traits are typical of networked digital movements? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Fast witness through phones or platforms" },
          { id: "b", text: "Low-barrier participation through tags and sharing" },
          { id: "c", text: "Guaranteed long-term institutional success" },
          { id: "d", text: "A need for offline organization if the movement wants durable change" },
        ],
        correct: ["a", "b", "d"],
        explanation: "Digital movements excel at fast attention and entry, but they still need offline organization, legal strategy, and coalition depth if they want to outlast the viral moment.",
        difficulty: "medium",
      },
    ],
  },
  {
    moduleSlug: "how-social-movements-reshape-history",
    title: "Social Movements Timeline",
    questions: [
      {
        id: "movetimeline-1",
        text: "Across very different eras, what combination most often turns a movement into a historic turning point?",
        kind: "single",
        options: [
          { id: "a", text: "A grievance plus new coordination tools, durable organization, and vulnerability in the existing order" },
          { id: "b", text: "A grievance alone, because organization is secondary" },
          { id: "c", text: "Only charismatic leadership, regardless of structure" },
          { id: "d", text: "Only repression, because it always strengthens movements" },
        ],
        correct: ["a"],
        explanation: "The timeline is built around a recurring pattern: grievance matters, but it has to be amplified through communication, organization, and some opening or fracture in the old order before it becomes durable historical change.",
        difficulty: "easy",
      },
      {
        id: "movetimeline-2",
        text: "What is the main lesson of comparing pamphlet-era, industrial, rights-based, and digital movements?",
        kind: "single",
        options: [
          { id: "a", text: "Every movement is so unique that comparison teaches very little" },
          { id: "b", text: "The communication technology changes, but the need for organization and institutional conversion does not disappear" },
          { id: "c", text: "Modern movements no longer need coalitions or institutions" },
          { id: "d", text: "Earlier movements were slower only because people cared less" },
        ],
        correct: ["b"],
        explanation: "The medium changes from print to television to platforms, but durable change still depends on whether the movement can survive repression, scale organization, and convert public pressure into institutions.",
        difficulty: "medium",
      },
      {
        id: "movetimeline-3",
        text: "Which conditions commonly make a movement stall rather than break through? (Select all that apply)",
        kind: "multi",
        options: [
          { id: "a", text: "Fast visibility without enough organizational depth" },
          { id: "b", text: "Very closed institutions with no channel for conversion" },
          { id: "c", text: "Heavy repression that stays hidden and does not backfire into a legitimacy crisis" },
          { id: "d", text: "A broad coalition and strong elite splits in the old order" },
        ],
        correct: ["a", "b", "c"],
        explanation: "Movements often stall when attention outruns organization, when institutions stay shut, or when coercion isolates the movement rather than delegitimizing the regime. Broad coalitions and elite splits usually help, not hurt.",
        difficulty: "medium",
      },
    ],
  },
];

export function getQuizBySlug(slug: string): ModuleQuiz | undefined {
  return moduleQuizzes.find((q) => q.moduleSlug === slug);
}

export function getAllQuizSlugs(): string[] {
  return moduleQuizzes.map((q) => q.moduleSlug);
}
