// AUTO-GENERATED — do not edit by hand.
// Source of truth: content/learn/modules/*.md frontmatter
// Regenerate: npm run gen:metadata
import type { AccentTone } from "./_types";

export type GeneratedMetadata = {
  accent: AccentTone;
  difficulty: string;
  eyebrow: string;
  readingTime: string;
  summary: string;
  title: string;
};

export const generatedMetadata: Record<string, GeneratedMetadata> = {
  "climate-solutions": {
    accent: "cyan",
    difficulty: "Intermediate",
    eyebrow: "Climate synthesis",
    readingTime: "8 min",
    summary: "The climate path asked whether growth can continue on a finite planet. The answer requires addressing measurement, decoupling, tipping points, and urban systems simultaneously.",
    title: "Pathways to Ecological Balance",
  },
  "democracy-solutions": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Democracy synthesis",
    readingTime: "9 min",
    summary: "Lobbying, electoral rules, corruption, short-termism, and institutional design all shape whether democracies solve problems. This capstone assembles what actually works.",
    title: "Strengthening Democracy",
  },
  "financial-crisis-solutions": {
    accent: "emerald",
    difficulty: "Advanced",
    eyebrow: "Financial crisis synthesis",
    readingTime: "7 min",
    summary: "The S&L crisis, the 2008 crash, and the broader pattern of repeating crises all trace back to the same structural faults. This capstone asks what genuinely breaks the cycle.",
    title: "Preventing Financial Crises",
  },
  "housing-solutions": {
    accent: "cyan",
    difficulty: "Intermediate",
    eyebrow: "Housing synthesis",
    readingTime: "7 min",
    summary: "Banking, land speculation, urban design, and wealth inequality all feed the housing crisis. This capstone draws together the reform agenda that addresses each driver.",
    title: "Making Housing Affordable Again",
  },
  "how-anti-colonial-movements-dismantled-empires": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Historical Movements",
    readingTime: "7 min",
    summary: "The dismantling of European empires in the twentieth century was one of history's largest political transformations — achieved through a combination of armed resistance, mass non-cooperation, legal challenge, and the strategic exploitation of Cold War geopolitics.",
    title: "How anti-colonial movements dismantled empires",
  },
  "how-banking-crises-repeat": {
    accent: "rose",
    difficulty: "Intermediate",
    eyebrow: "Financial Systems",
    readingTime: "6 min",
    summary: "Banking crises look different each time — different assets, different institutions, different decades — but the underlying structure repeats: leverage, interconnection, and the socialisation of losses.",
    title: "How banking crises repeat",
  },
  "how-banks-create-money": {
    accent: "cyan",
    difficulty: "Starter",
    eyebrow: "Financial System Design",
    readingTime: "7 min",
    summary: "Commercial banks do not lend out existing deposits — they create new money by issuing loans, making private credit decisions a form of economic policy.",
    title: "How banks create money",
  },
  "how-capitalism-socialism-and-communism-differ": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Political Economy",
    readingTime: "8 min",
    summary: "These three terms describe different answers to the same questions about ownership, investment, and access — not a simple spectrum from bad to good or free to unfree.",
    title: "How capitalism, socialism, and communism differ",
  },
  "how-companies-engineer-public-opinion-through-marketing": {
    accent: "rose",
    difficulty: "Intermediate",
    eyebrow: "Public opinion design",
    readingTime: "10 min",
    summary: "Corporate marketing can do more than sell products: it can borrow movement language, shape norms, and reorganize public opinion by tying consumption to identity and freedom.",
    title: "How companies engineer public opinion through marketing",
  },
  "how-corruption-behaves-like-a-hidden-tax": {
    accent: "rose",
    difficulty: "Starter",
    eyebrow: "Institutional integrity",
    readingTime: "6 min",
    summary: "Corruption quietly increases costs, delays, and uncertainty across the system, much like an unofficial tax that buys worse outcomes.",
    title: "How corruption behaves like a hidden tax",
  },
  "how-doughnut-economics-puts-the-economy-inside-limits": {
    accent: "emerald",
    difficulty: "Starter",
    eyebrow: "Ecological economics",
    readingTime: "8 min",
    summary: "Doughnut economics asks whether society keeps everyone above a social foundation while staying below ecological ceilings. It shifts the question from how fast the economy grows to whether it remains socially fair and biophysically viable.",
    title: "How Doughnut economics puts the economy inside limits",
  },
  "how-electoral-rules-shape-political-power": {
    accent: "cyan",
    difficulty: "Beginner",
    eyebrow: "Political system",
    readingTime: "6 min",
    summary: "Electoral system design determines how votes translate into representation — and the rules are maintained by those who benefit most from the current design.",
    title: "How electoral rules shape political power",
  },
  "how-industrial-mass-movements-won-rights": {
    accent: "emerald",
    difficulty: "Intermediate",
    eyebrow: "Historical Movements",
    readingTime: "7 min",
    summary: "The eight-hour day, the weekend, child labour laws, workplace safety standards — these were not given by governments or employers. They were extracted through decades of organised industrial action, at significant personal cost to the people who organised.",
    title: "How industrial mass movements won rights",
  },
  "how-lobbying-shapes-policy": {
    accent: "amber",
    difficulty: "Starter",
    eyebrow: "Political influence",
    readingTime: "6 min",
    summary: "Influence usually works through access, repetition, and carve-outs, not just dramatic corruption scandals.",
    title: "How lobbying shapes policy",
  },
  "how-media-incentives-produce-outrage": {
    accent: "rose",
    difficulty: "Starter",
    eyebrow: "Media systems",
    readingTime: "8 min",
    summary: "Attention markets often reward emotional escalation, which can increase engagement while degrading trust and nuance.",
    title: "How media incentives produce outrage",
  },
  "how-networked-digital-movements-scale": {
    accent: "cyan",
    difficulty: "Intermediate",
    eyebrow: "Movement families",
    readingTime: "8 min",
    summary: "Networked movements scale through fast witness and low participation costs, but their historic impact depends on whether viral attention is converted into durable institutions and enforceable change.",
    title: "How networked movements scale through digital media",
  },
  "how-pollution-builds-up-until-systems-tip": {
    accent: "cyan",
    difficulty: "Starter",
    eyebrow: "Systems risk",
    readingTime: "8 min",
    summary: "Pollution becomes a systems risk when it accumulates faster than the environment can absorb it. Delayed feedback hides the danger, resilience erodes quietly, and then change can become abrupt and harder to reverse.",
    title: "How pollution builds up until systems tip",
  },
  "how-print-era-movements-turned-ideas-into-power": {
    accent: "cyan",
    difficulty: "Intermediate",
    eyebrow: "Historical Movements",
    readingTime: "6 min",
    summary: "The printing press didn't just spread information — it created new kinds of political possibility. Movements that mastered the new medium rewrote the terms of religious authority, political legitimacy, and collective identity for centuries.",
    title: "How print era movements turned ideas into power",
  },
  "how-rights-based-movements-expand-citizenship": {
    accent: "rose",
    difficulty: "Intermediate",
    eyebrow: "Movement families",
    readingTime: "8 min",
    summary: "Rights-based movements expand citizenship when visible injustice, broad coalitions, and disciplined disruption are converted into enforceable reforms rather than left as temporary moral outrage.",
    title: "How rights-based movements expand citizenship",
  },
  "how-social-movements-reshape-history": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Movement synthesis",
    readingTime: "9 min",
    summary: "From pamphlets to hashtags, movements repeatedly change history when new coordination tools, durable organization, and elite vulnerability combine strongly enough to turn grievance into institutional transformation.",
    title: "How social movements reshape history",
  },
  "how-surveillance-capitalism-shapes-attention": {
    accent: "rose",
    difficulty: "Beginner",
    eyebrow: "Information system",
    readingTime: "9 min",
    summary: "Surveillance capitalism turns human behavioral data into prediction products sold to influence behavior — with outrage amplification as a structural side effect of the business model.",
    title: "How surveillance capitalism shapes attention",
  },
  "how-tax-havens-drain-public-revenue": {
    accent: "emerald",
    difficulty: "Intermediate",
    eyebrow: "Global Finance",
    readingTime: "7 min",
    summary: "Tax havens are not a side effect of global finance — they are an engineered system that shifts the tax burden from mobile capital onto workers and consumers.",
    title: "How tax havens drain public revenue",
  },
  "how-the-2008-financial-crisis-happened": {
    accent: "rose",
    difficulty: "Intermediate",
    eyebrow: "Financial History",
    readingTime: "8 min",
    summary: "The 2008 crisis was not a random shock — it was the predictable outcome of deregulation, leverage, and misaligned incentives that regulators and rating agencies failed to address.",
    title: "How the 2008 financial crisis happened",
  },
  "how-the-eu-makes-decisions": {
    accent: "cyan",
    difficulty: "Starter",
    eyebrow: "European Governance",
    readingTime: "7 min",
    summary: "EU decisions require alignment between the Commission, Parliament, and Council — a design that distributes power but also slows reform and gives well-organised interests multiple points to apply pressure.",
    title: "How the EU makes decisions",
  },
  "how-the-us-government-makes-decisions": {
    accent: "rose",
    difficulty: "Starter",
    eyebrow: "American Governance",
    readingTime: "7 min",
    summary: "The US system was designed to make passing laws difficult. That design increasingly protects the status quo regardless of public opinion.",
    title: "How the US government makes decisions",
  },
  "how-the-us-rewrites-the-rules-of-money": {
    accent: "cyan",
    difficulty: "Advanced",
    eyebrow: "Global Finance",
    readingTime: "7 min",
    summary: "The US dollar's dominance was not an accident — it was built through specific, deliberate rule-rewrites. Understanding those moments reveals how monetary architecture is a political choice, not a natural fact.",
    title: "How the US rewrites the rules of money",
  },
  "how-wealth-compounds-faster-than-wages": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Economic system",
    readingTime: "7 min",
    summary: "When the return on capital consistently exceeds economic growth, existing wealth compounds faster than wages rise, structurally widening inequality over time.",
    title: "How wealth compounds faster than wages",
  },
  "inequality-solutions": {
    accent: "rose",
    difficulty: "Intermediate",
    eyebrow: "Inequality synthesis",
    readingTime: "8 min",
    summary: "Wealth compounds faster than wages, tax havens shelter it, lobbying protects it, and electoral rules insulate it from accountability. This capstone asks what breaks the cycle.",
    title: "Tackling Wealth and Power Concentration",
  },
  "media-solutions": {
    accent: "rose",
    difficulty: "Intermediate",
    eyebrow: "Media synthesis",
    readingTime: "7 min",
    summary: "PR manufactures consent, outrage algorithms shape discourse, surveillance capitalism monetises attention. This capstone asks what a healthier information environment requires.",
    title: "Reclaiming the Information Environment",
  },
  "money-solutions": {
    accent: "emerald",
    difficulty: "Advanced",
    eyebrow: "Money synthesis",
    readingTime: "8 min",
    summary: "Banks create money, wealth compounds, profits escape taxation, and the US sets global monetary rules. This capstone asks what a reformed monetary system looks like.",
    title: "Reforming Money and Banking",
  },
  "movements-solutions": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Movements synthesis",
    readingTime: "8 min",
    summary: "From the printing press to the smartphone, the history of movements shows consistent patterns of success and failure. This capstone draws the strategic lessons.",
    title: "Building Movements That Last",
  },
  "pathways-to-change": {
    accent: "emerald",
    difficulty: "Intermediate",
    eyebrow: "Systems change",
    readingTime: "10 min",
    summary: "Every system problem explored in this atlas has been addressed somewhere. This module asks what it actually takes to make structural reform happen — and assembles the precedents, coalitions, and conditions that turn diagnosis into change.",
    title: "Pathways to change",
  },
  "the-savings-and-loan-crisis-of-the-1980s": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Financial History",
    readingTime: "6 min",
    summary: "The S&L crisis was a dress rehearsal for 2008 — deregulation created the conditions for reckless lending, and when the losses came due, taxpayers paid while executives kept their gains.",
    title: "The savings and loan crisis of the 1980s",
  },
  "wellbeing-solutions": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Wellbeing synthesis",
    readingTime: "7 min",
    summary: "GDP can grow while wellbeing stagnates. The modules in this path asked why — and the answers point toward a coherent reform agenda for measuring and producing what actually matters.",
    title: "Building Economies That Serve Wellbeing",
  },
  "why-capable-people-dont-enter-politics": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Political Systems",
    readingTime: "6 min",
    summary: "The people who could govern well are systematically selected against. The skills and traits that help you win elections are different from the skills and traits that help you govern effectively — and the gap between them is growing.",
    title: "Why capable people don't enter politics",
  },
  "why-cities-create-stress-or-freedom": {
    accent: "emerald",
    difficulty: "Starter",
    eyebrow: "Urban systems",
    readingTime: "6 min",
    summary: "Urban design can either tax people with distance and friction or create calm, flexibility, and local freedom.",
    title: "Why cities create stress or freedom",
  },
  "why-decoupling-growth-from-emissions-is-so-hard": {
    accent: "emerald",
    difficulty: "Intermediate",
    eyebrow: "Ecological Economics",
    readingTime: "7 min",
    summary: "Global emissions hit a record in 2023 while renewable energy grew faster than ever. That apparent paradox explains why decoupling economic growth from ecological damage is fundamentally harder than optimism about technology suggests.",
    title: "Why decoupling growth from emissions is so hard",
  },
  "why-democracies-struggle-with-long-term-problems": {
    accent: "amber",
    difficulty: "Intermediate",
    eyebrow: "Political Systems",
    readingTime: "6 min",
    summary: "Democracies are good at responding to immediate pressure. They are structurally weak at acting on problems that mature over decades — not because politicians lack knowledge, but because the incentive structure punishes it.",
    title: "Why democracies struggle with long-term problems",
  },
  "why-gdp-is-not-the-same-as-wellbeing": {
    accent: "cyan",
    difficulty: "Starter",
    eyebrow: "Economic measurement",
    readingTime: "7 min",
    summary: "GDP can climb while people become more stressed, less healthy, less secure, and less able to afford a decent life.",
    title: "Why GDP is not the same as wellbeing",
  },
  "why-housing-becomes-financialized": {
    accent: "rose",
    difficulty: "Starter",
    eyebrow: "Housing and Political Economy",
    readingTime: "7 min",
    summary: "When housing is treated as a financial asset rather than a social need, prices rise structurally faster than wages and access narrows regardless of how hard people work.",
    title: "Why housing becomes financialized",
  },
};
