import type { LearningModule } from "./_types";

export const lessonData: LearningModule = {
    betterMetrics: [
      {
        label: "Shadow banking ratio",
        description: "Assets held by unregulated institutions as a fraction of total financial system assets. A rising ratio signals growing systemic fragility outside the regulatory perimeter.",
      },
      {
        label: "Leverage-adjusted capital buffer",
        description: "Bank equity as a % of total assets (not risk-weighted). Simple, hard to game, and the best single predictor of whether a bank survives a crisis.",
      },
      {
        label: "Time since last crisis",
        description: "A counter-intuitive metric: long stability periods correlate with rising systemic risk, as regulatory memory fades and leverage accumulates.",
      },
    ],
    betterMetricsTitle: "Better measures of systemic financial risk",
    counterArguments: [
      {
        point: "Modern finance is too complex to regulate like 1930s banking. Derivatives and securitisation serve real economic needs.",
        response: "The complexity argument is often made by those who benefit from complexity. The 2008 crisis showed that instruments too complex to value or understand are instruments too complex to regulate — and therefore instruments that should not be permitted in systemically important institutions. Simplicity is a feature, not a limitation.",
        title: "Complexity is progress",
      },
      {
        point: "Bailouts create moral hazard. We should let banks fail so markets can discipline risk-taking.",
        response: "In theory correct. In practice, the interconnection of modern finance means a disorderly bank failure immediately threatens the payments system, credit supply, and pension funds — hitting ordinary people first. The solution is not to abandon bailouts but to prevent the conditions that make them unavoidable: higher capital requirements, living wills, and credible resolution regimes that wipe out shareholders before taxpayers pay.",
        title: "Let them fail — moral hazard",
      },
      {
        point: "Strong banking regulation just pushes risk into less regulated shadow banking.",
        response: "This is the 'whack-a-mole' critique, and historically it has merit. The response is to regulate by function, not by institutional label: any institution that takes deposits, creates leverage, and promises liquidity should face bank-equivalent oversight — regardless of whether it calls itself a hedge fund, a money market fund, or a trust.",
        title: "Regulation just moves risk",
      },
    ],
    causalLoop: {
      description: "Banking crises follow a recurrent loop: stability breeds complacency, which weakens regulation, which enables shadow banking and leverage, which inflates bubbles, which eventually collapse into crises that prompt re-regulation — until the memory fades and the cycle restarts.",
      edges: [
        { from: "stability", to: "complacency", label: "+", polarity: "positive" as const },
        { from: "complacency", to: "regGap", label: "+", polarity: "positive" as const },
        { from: "regGap", to: "shadow", label: "+", polarity: "positive" as const },
        { from: "shadow", to: "leverage", label: "+", polarity: "positive" as const },
        { from: "leverage", to: "assetPrices", label: "+", polarity: "positive" as const },
        { from: "assetPrices", to: "leverage", label: "+", polarity: "positive" as const, bend: 0.4 },
        { from: "leverage", to: "fragility", label: "+", polarity: "positive" as const },
        { from: "fragility", to: "crisis", label: "+", polarity: "positive" as const },
        { from: "crisis", to: "regulation", label: "+", polarity: "positive" as const },
        { from: "regulation", to: "regGap", label: "−", polarity: "negative" as const },
        { from: "crisis", to: "stability", label: "−", polarity: "negative" as const, bend: -0.3 },
      ],
      loops: ["R1 — Leverage spiral (leverage ↔ asset prices)", "B1 — Regulatory response (crisis → new rules)", "R2 — Stability–complacency–deregulation (the 30-year cycle)"],
      nodes: [
        { id: "stability", label: "Stability & growth", x: 200, y: 30, tone: "cyan" as const },
        { id: "complacency", label: "Regulatory complacency", x: 340, y: 100, tone: "amber" as const },
        { id: "regGap", label: "Regulatory gap", x: 340, y: 200, tone: "amber" as const },
        { id: "shadow", label: "Shadow banking growth", x: 260, y: 290, tone: "rose" as const },
        { id: "leverage", label: "Leverage & speculation", x: 140, y: 290, tone: "rose" as const },
        { id: "assetPrices", label: "Asset price bubble", x: 60, y: 200, tone: "rose" as const },
        { id: "fragility", label: "Systemic fragility", x: 60, y: 110, tone: "rose" as const },
        { id: "crisis", label: "Crisis & contagion", x: 140, y: 30, tone: "rose" as const },
        { id: "regulation", label: "New regulation", x: 340, y: 30, tone: "emerald" as const },
      ],
      title: "The Banking Crisis Cycle",
    },
    discussionPrompt: "If regulators know this pattern — stability → complacency → shadow banking → crisis — why does it keep repeating? Is the problem a failure of knowledge, a failure of political will, or a structural feature of how financial regulation is captured by the industry it oversees?",
    heroHighlights: [
      "Every major financial crisis since 1907 has involved institutions operating as banks without bank-level regulation.",
      "Deposit insurance broke the retail bank run loop — but shadow banking recreated the same vulnerability outside its perimeter.",
      "The cycle of crisis → regulation → stability → complacency → deregulation → crisis repeats roughly every 30 years.",
    ],
    miniLesson: {
      bands: [
        { threshold: 8,  insight: "At 8× leverage, a 12.5% asset decline wipes out equity. This is typical commercial banking. Manageable if reserves and capital buffers are adequate." },
        { threshold: 20, insight: "At 20× leverage, a 5% asset price fall causes insolvency. Many banks operated here before 2008. A modest housing correction becomes an existential crisis." },
        { threshold: 33, insight: "At 33× leverage — where Lehman Brothers operated in 2008 — a 3% asset decline destroys the bank. This is not a margin for error. It is a guaranteed failure waiting for a trigger." },
        { threshold: 45, insight: "At 45× leverage, the institution is effectively a bet that nothing will ever go wrong by even 2%. LTCM operated here in 1998 before collapsing and nearly taking global markets with it." },
      ],
      defaultValue: 10,
      description: "Leverage amplifies everything: in a boom, it turbocharges returns. In a bust, it turbocharges losses. Adjust the slider to see how the same 5% asset price decline affects a bank depending on its leverage ratio.",
      highLabel: "Highly leveraged (Lehman 2008 level)",
      lowLabel: "Conservative (equity-funded)",
      metrics: [
        {
          key: "roe",
          label: "Return on equity (5% asset return year)",
          description: "Annual profit as % of equity when assets return 5%",
          base: 0,
          slope: 5,
          min: 5,
          max: 250,
          tone: "emerald" as const,
          suffix: "%",
        },
        {
          key: "insolvency_threshold",
          label: "Asset decline before insolvency",
          description: "How far asset prices can fall before equity is wiped out",
          base: 102,
          slope: -2,
          min: 1,
          max: 100,
          tone: "rose" as const,
          suffix: "%",
        },
        {
          key: "taxpayer_risk",
          label: "Systemic risk to taxpayers",
          description: "Likelihood that a failure requires public bailout",
          base: 0,
          slope: 2,
          min: 0,
          max: 100,
          tone: "amber" as const,
          suffix: "%",
        },
      ],
      prompt: "Move the slider to explore how leverage changes the risk profile of a financial institution.",
      sliderLabel: "Leverage ratio",
      step: 1,
      title: "The Leverage Trade-off",
      unit: "×",
      valueLabel: "Leverage",
      valueMax: 50,
      valueMin: 1,
    },
    realWorldExamples: [
      {
        title: "Panic of 1907 — The Original Shadow Bank",
        outcome: "New York 'trusts' acted like banks — accepting deposits, speculating in stocks — but faced no reserve requirements and no clearinghouse backing. When the Knickerbocker Trust collapsed, panic spread to all trusts within days. J.P. Morgan personally organised a rescue. The US entered a four-year recession. Output fell 11%, unemployment rose to 8%.",
        insight: "The 1907 panic was caused not by a regulated bank but by an institution that looked like a bank, acted like a bank, but escaped bank regulation. This pattern — shadow institutions taking bank risks — would repeat in every major crisis that followed.",
      },
      {
        title: "S&L Crisis 1980s — Deregulation + Deposit Insurance = Disaster",
        outcome: "Congress deregulated savings & loans in 1980, allowing them to make risky real estate bets while keeping federal deposit insurance. Executives gambled freely — losses were the government's problem. Over 1,000 S&Ls failed between 1986–1995, costing US taxpayers $124 billion. The resulting credit crunch contributed to the 1990 recession.",
        insight: "Moral hazard in its purest form: privatise the gains, socialise the losses. Deposit insurance is essential to prevent panics — but it must be paired with strict oversight, or it becomes a subsidy for recklessness.",
      },
      {
        title: "2008 Global Financial Crisis — Leverage × Shadow Banking × No Memory",
        outcome: "Investment banks at 30:1 leverage held securitised subprime mortgages they couldn't value. Shadow institutions — SIVs, money market funds, broker-dealers — held more assets than regulated banks but had no deposit insurance and no Fed backstop. When Lehman Brothers failed in September 2008, global credit froze within 72 hours. GDP fell in every major economy. 8 million jobs were lost in the US alone.",
        insight: "2008 was 1907 repeated at a scale orders of magnitude larger, enabled by financial innovation that outpaced regulatory imagination. The Glass-Steagall Act — designed precisely to prevent this — had been gutted by 1999.",
      },
    ],
    relatedFrameworks: [
      "Hyman Minsky — financial instability hypothesis",
      "Walter Bagehot — lender of last resort",
      "Glass-Steagall Act 1933 (and its 1999 repeal)",
      "Basel III capital requirements",
      "Shadow banking and regulatory arbitrage",
      "Too big to fail / too connected to fail",
    ],
    simulationPrompt: "Set reserve ratios, deposit insurance coverage, and central bank response speed to test whether your regulatory design would have contained the 1907 panic or the 2008 collapse.",
    simulatorSlug: "bank-run",
    slug: "how-banking-crises-repeat",
    simpleExplanation: [
      "Banking crises are not accidents — they are the predictable output of a system that rewards risk-taking in good times and socialises losses in bad ones. Every major crisis since 1907 has followed the same basic script: a period of stability breeds complacency, regulation is loosened, institutions take on more leverage, and eventually a shock reveals that the safety net was an illusion.",
      "The self-fulfilling nature of bank runs is the key mechanism. Banks borrow short and lend long — they take deposits that can be withdrawn today and make loans that mature over years. If enough depositors believe others will withdraw, it becomes rational for everyone to withdraw simultaneously, even from a perfectly solvent bank. Deposit insurance was invented specifically to break this panic loop by removing the first-mover advantage.",
      "What changes across each crisis is not the mechanism but the venue. In 1907 it was unregulated trust companies. In the 1980s it was savings and loans given investment powers without capital requirements. In 2008 it was a shadow banking system operating at bank-like leverage without bank-like oversight. In 2023 it was concentrated uninsured deposits and duration-mismatched bond portfolios. The regulatory perimeter keeps moving; the underlying dynamic does not.",
    ],
    systemBug: {
      signals: [
        "Shadow banking sector grows faster than regulated banking between crises",
        "Leverage ratios at major institutions rise steadily during boom periods",
        "Regulatory bodies staffed by former or future industry employees",
        "Crisis-era legislation progressively weakened during periods of stability",
        "Complexity of financial instruments outpaces regulators' ability to value them",
      ],
      summary: "The financial system is structured so that those who take risks are not those who pay for failure. Profits flow to shareholders and executives during booms; losses flow to taxpayers and employees during busts. This asymmetry creates a permanent incentive to take excessive risk — and a permanent political pressure to weaken the regulation that constrains it.",
      title: "System bug: private risk, public losses — the moral hazard loop",
    },
  proposals: [
    {
      title: "Establish automatic countercyclical capital buffers tied to credit growth",
      summary: "Banks become fragile during booms because capital ratios fall as asset prices rise. Countercyclical buffers automatically raising capital requirements when private credit grows faster than GDP force banks to build resilience in good times.",
      actor: "national_gov",
      domain: "economic",
      feasibility: "proven",
      precedents: [
        { place: "Sweden", year: 2015, outcome: "CCyB deployed when mortgage credit surged; released in 2020 to absorb COVID shock — system remained stable" },
        { place: "UK", year: 2022, outcome: "Bank of England raised CCyB to 2%; released March 2020 providing 23bn pounds of lending capacity" },
      ],
    },
    {
      title: "Create a public bank as a stable, countercyclical lender",
      summary: "Private banks cut lending simultaneously during crises, deepening recessions. Public banks with an explicit public mandate maintain lending when it is needed most, acting as automatic stabilisers without requiring emergency bailouts.",
      actor: "national_gov",
      domain: "economic",
      feasibility: "proven",
      precedents: [
        { place: "Germany (KfW)", year: 1948, outcome: "State development bank countercyclically expanded lending in every recession; supported SMEs through 2008 when private banks froze" },
        { place: "North Dakota (BND)", year: 1919, outcome: "Only US state-owned bank; North Dakota was the only state with budget surplus in 2009" },
      ],
    },
    {
      title: "Separate retail deposit-taking from proprietary trading",
      summary: "When the same institution takes insured deposits and makes speculative bets, losses in trading become a public liability. Hard separation ensures depositors savings are never exposed to casino-banking risk.",
      actor: "national_gov",
      domain: "legal",
      feasibility: "contested",
      precedents: [
        { place: "USA (Glass-Steagall)", year: 1933, outcome: "Separation held from 1933 to 1999 — no systemic banking crisis during that period; repeal followed by crisis within a decade" },
        { place: "EU (Liikanen Report)", year: 2012, outcome: "Proposed mandatory separation for EU banks with large trading books; established the structural reform case" },
      ],
    },
  ],

  };
